src/shared/components/navbar.tsx, src/shared/components/search.tsx
This fixes the search for URLs like `http://lemmy-beta:8551/c/main`, and correctly displays the community in the search results. Both when searching from the navbar and from the search page.
I also tested the HTTP API using `curl "http://localhost:8540/api/v1/search?q=test%3F&type_=All&sort=TopAll"`, which is logged on the backend as `q: "test?"`, so it looks like actix is already decoding parameters for us, and we dont have to change anything there.
I think this also needs to be fixed [here in lemmy-js-client](https://github.com/LemmyNet/lemmy-js-client/blob/main/src/http.ts#L137).
=> Use urlencode for search queries (fixes #10)

Dockerfile
I got this error when building:
`When using COPY with more than one source file, the destination must be a directory and end with a /`
=> COPY requires / suffix

src/shared/components/comment-node.tsx, src/shared/components/comment-nodes.tsx, src/shared/components/community.tsx, src/shared/components/main.tsx, src/shared/components/post-listings.tsx, src/shared/components/post.tsx, src/shared/utils.ts
- Only changing the view or sort, or reloading the page will resort.
- New comments by default added to the top, and left unsorted.
=> Comments and posts no longer live-sorted. Fixes #51

src/server/index.tsx
At the moment the process listens on localhost, hard coded. This makes it hard for me to deploy in Kubernetes.
So I would very much appreciate if the server could take listen host and port from environment.
=> Set listen host and port with environment variables

src/server/index.tsx
Reasoning for patch:
Some search engines and crawler bots rely on the robots.txt file to know what parts of the site to crawl or not crawl. Without one, it will proceed to crawl the entire site by deafult. However, it doesn't make sense for bots to crawl parts that require a login or are user directed , like "create_community" or "login". Some poorly programmed bots will constantly hit an endpoint that doesn't make sense, causing general slowness for everyone.
Suggestions for other protected endpoints welcome.
=> Add robots.txt file

src/shared/utils.ts
Hi,  I deployed an instance in another language and found that when posting , the form comminity displays the  community ID instead of its display name, but it's a bit inconvenient for non-native English instances, so I submitted the PR.
I can close this PR if you don't think you need it, and it will only work for my instance.
Thanks!
=> Post form community name using title instead of name

src/shared/components/app/navbar.tsx
Remove touch events, it breaks clicking links on mobile. Tested this on a iphone 7
=> Remove touch events

src/shared/components/footer.tsx, src/shared/components/navbar.tsx
there is some issue with `title` attribute. So it will not pass the lint, but everything is working fine. Since `NavLink` only accepted `NavLinkProps`, this is issue with the `inferno-router` itself. .
=> Change from using Link to NavLink. resolve #269

package.json, src/shared/components/app/navbar.tsx, src/shared/components/common/moment-time.tsx, src/shared/components/person/settings.tsx, src/shared/i18next.ts, src/shared/utils.ts, yarn.lock
As described in https://github.com/LemmyNet/joinlemmy-site/pull/76#issuecomment-1040200021
There is still a problem in that all language names are rendered left to right, even those which should be rtl (like Arabic).
=> Fix language names

src/shared/components/comment/comment-node.tsx
Unlike what the comment says, comment ap_ids are not broken at all. The only problem is that no frontend endpoint exists for that url. But if you want to e.g. fetch a specific Lemmy comment from Mastodon and respond to it, this fedilink is the only way (as the normal link `/post/123/comment/456` doesnt work for that).
=> Fix comment fedilink (fixes #594)

src/shared/components/search.tsx, src/shared/utils.ts
The loading indicator on the search page is broken, because loading is set to false when `SearchResponse` is received, but we may still be waiting for `ResolveObjectResponse`. This is especially problematic when resolving a remote community, which takes a long time, so it appears that the search failed (also see https://github.com/LemmyNet/lemmy/pull/2181).
This PR adds an explicit check to remove the loading indicator only when both responses have been received.
=> Fix loading indicator on search page (fixes #443)

src/server/index.tsx
The current implementation is broken due to wrong encoding, and doesnt apply to all endpoints.
`<meta http-equiv="Content-Security-Policy" content="default-src data: &#039;self&#039;; connect-src * ws: wss:; frame-src *; img-src * data:; script-src &#039;self&#039;; style-src &#039;self&#039; &#039;unsafe-inline&#039;; manifest-src &#039;self&#039">`
=> Set content security policy http header for all responses

src/shared/components/community/community.tsx, src/shared/components/person/profile.tsx
If the community identifier in url can be interpreted as a valid integer, lemmy-ui considers it as community id, which breaks things if a community has a name with only numbers.
=> Dont allow community urls like /c/{id} (fixes #611)

package.json, src/shared/components/community/community.tsx, src/shared/components/home/home.tsx, src/shared/components/home/site-form.tsx, src/shared/components/home/site-sidebar.tsx, yarn.lock
This has limitations: 
Since only the site, and not the site_view, or admins, come back from GetCommunity, it really only shows the sidebar, and no activity counts.
=> Adding site sidebar for remote communities. Fixes #626

package.json, src/shared/components/community/community-form.tsx, src/shared/components/community/create-community.tsx, src/shared/components/community/sidebar.tsx, src/shared/components/post/post-form.tsx, yarn.lock
This adds the setting to the community form, as well as hides the create post button on the community for non-mods if the setting is enabled.
=> Add posting restricted to mods

src/shared/components/home/home.tsx
Site from scratch in *dev* mode resulted in NPE on *home.tsx* that prevented anything to show up.
```
TypeError: Cannot read properties of null (reading 'site')
at new Home (webpack://lemmy-ui/./src/shared/components/home/home.tsx?:73:188)
at renderVNodeToString (/tmp/lemmy-ui/node_modules/inferno-server/dist/index.cjs.js:170:28)
at renderVNodeToString (/tmp/lemmy-ui/node_modules/inferno-server/dist/index.cjs.js:221:20)
at renderVNodeToString (/tmp/lemmy-ui/node_modules/inferno-server/dist/index.cjs.js:221:20)
at renderVNodeToString (/tmp/lemmy-ui/node_modules/inferno-server/dist/index.cjs.js:303:35)
at renderVNodeToString (/tmp/lemmy-ui/node_modules/inferno-server/dist/index.cjs.js:307:39)
at renderVNodeToString (/tmp/lemmy-ui/node_modules/inferno-server/dist/index.cjs.js:221:20)
at …
```
=> Fix NPE during new site startup

src/shared/i18next.ts
This pull request fixed issue [#667](https://github.com/LemmyNet/lemmy-ui/issues/667).
=> Use zh-TW for language code, instead of zh_Hant.

src/server/index.tsx
Also change the env var name to LEMMY_UI_DISABLE_CSP as debug with csp generally works fine now, and this name is much clearer.
=> Change CSP rule for connect-src (websocket) to wildcard (fixes #730)

src/assets/css/main.css, src/shared/components/home/site-form.tsx, src/shared/components/modlog.tsx, src/shared/utils.ts
See https://github.com/LemmyNet/lemmy/pull/2313
=> Add Modlog Filters

src/shared/components/app/footer.tsx, src/shared/components/app/navbar.tsx, src/shared/components/app/no-match.tsx, src/shared/components/community/communities.tsx, src/shared/components/community/community.tsx, src/shared/components/community/create-community.tsx, src/shared/components/home/admin-settings.tsx, src/shared/components/home/home.tsx, src/shared/components/home/instances.tsx, src/shared/components/home/legal.tsx, src/shared/components/home/login.tsx, src/shared/components/home/setup.tsx, src/shared/components/home/signup.tsx, src/shared/components/modlog.tsx, src/shared/components/person/inbox.tsx, src/shared/components/person/password-change.tsx, src/shared/components/person/profile.tsx, src/shared/components/person/registration-applications.tsx, src/shared/components/person/reports.tsx, src/shared/components/person/settings.tsx, src/shared/components/person/verify-email.tsx, src/shared/components/post/create-post.tsx, src/shared/components/post/post.tsx, src/shared/components/private_message/create-private-message.tsx, src/shared/components/search.tsx
This change will fix #799 and give 100% width for lemmy-ui on medium screen sizes.
Source: https://www.w3schools.com/bootstrap4/bootstrap_containers.asp
=> Change for container divs to container-lg

src/assets/css/main.css, src/shared/components/app/navbar.tsx
This is a set of style fixes for the search button and its associated input fields, based on the issues brought up in #500. 
- The search input jumps out of place when expanded: I could only reproduce this one by making my browser screen as small as possible without making the search button disappear, which can technically still occur with the proposed solution. Nonetheless, I thought it could be mitigated a small bit by making the search bar width dependent on view width.
- Search button is misaligned compared to the other navbar elements: This was fixed by reducing the margin on the right of the button.
- Search button has the wrong color: This was fixed by wrapping the existing HTML in the same list tags and CSS classes as all the other navigation bar items.
- Input field still …
=> Search button and input style fixes

src/shared/services/UserService.ts
Use hostname without port for setting empty cookie, avoids error in browser:  Cookie “jwt” has been rejected for invalid domain. Fixes https://github.com/LemmyNet/lemmy-ui/issues/819
=> Fix workaround for broken logout

package.json, src/assets/css/main.css, src/shared/components/home/home.tsx, src/shared/components/home/site-form.tsx, src/shared/utils.ts
See: https://github.com/LemmyNet/lemmy/pull/2548
Adds frontend support for Taglines.
Taglines are edited and displayed as Markdown. Screenshots Below:
Homepage:
Admin Settings:
=> Add Taglines support

package.json, src/shared/components/community/community.tsx, src/shared/components/home/home.tsx, src/shared/components/modlog.tsx, src/shared/components/person/profile.tsx, src/shared/components/post/post-listing.tsx, src/shared/components/post/post.tsx, src/shared/utils.ts
See https://github.com/LemmyNet/lemmy/pull/2585
Adds a new 'Pin' icon to pin to Local view
Marking as draft, as its still a bit unfinished. 
Also, soliciting feedback on what the Icon should look like. I'm not a fan of both 'pin to community' and 'pin to local' having the same icon. Not sure what other icons are available currently.
=> Add FeaturedPosts support

src/shared/components/app/app.tsx
Fixes #204. There's already a style block for `#app` so this just sets the id so those styles are applied.
=> Add `id` to `App` component

src/shared/components/search.tsx
=> fix: Make search screen able to change type, listing type, and sort when there is no query.

src/shared/components/home/admin-settings.tsx, src/shared/components/home/site-form.tsx, src/shared/components/home/tagline-form.tsx
This work moves the tagline editing from the main Site Settings form into its own tab, like emojis. It also is optimized for larger lists, allowing hundreds of taglines without slowing down the page.
I wrote this up pretty quick, didn't want to refactor too much, just needed to get past a blocker for hexbear. Its still worthy of upstreaming it, though, as current implementation falls apart if you have lots of taglines.
=> Optimize Tagline Form page

generate_translations.js, src/shared/components/app/no-match.tsx, src/shared/components/home/signup.tsx
While working on a translation issue, I thought it would be helpful for Typescript to say which parameters are needed for an i18 translation. 
Translations that don't require parameters are the same as before. However, if a translation needs parameters, Typescript will show an error if it's not getting them. In addition to that, Typescript will show which properties are needed on the parameter object. This screenshot shows an example:
As you can see, the `cake_day_info` translation requires a `creator_name` property to work.
=> I18 quality of life change

.prettierignore, package.json, src/shared/components/common/emoji-picker.tsx, src/shared/components/common/language-select.tsx, src/shared/components/common/markdown-textarea.tsx, src/shared/components/common/progress-bar.tsx, src/shared/components/home/emojis-form.tsx, src/shared/components/post/post-form.tsx, src/shared/utils.ts
This closes #777
This does what #812 by @sam365724 does but using the updated client.
=> Multiple image upload

src/shared/components/community/create-community.tsx, src/shared/components/community/sidebar.tsx, src/shared/components/person/profile.tsx, src/shared/components/post/create-post.tsx
This is for #975.
The community sidebar shows this when logged out:
The profile page looks like this:
The text being used isn't final and I'll gladly change it if anyone has any better ideas. The alerts seems somewhat bland at the moment too. Maybe there should be an icon to go with them?
I have also made a version of this PR where I hide the create post and create community buttons. I will make a separate PR for that.
=> Handle when logged out

src/assets/css/main.css, src/shared/components/community/sidebar.tsx, src/shared/components/modlog.tsx, src/shared/routes.ts
This is the PR for #991. 
This is what it looks like on a desktop:
This is what it looks like on mobile:
Translation PR will be made soon.
In addition to the content warning, I also fixed a bug I introduced in the query param PR regarding routing for community specific modlogs.
=> Add content warning to modlog and fix modlog routing bug

package.json, yarn.lock
This bumps the version of the JS client to include the serialization fix.
=> Update JS client to version with fixed JSON serialization

src/shared/components/comment/comment-form.tsx, src/shared/components/common/language-select.tsx, src/shared/components/post/post-form.tsx, src/shared/utils.ts
Lemmy-ui currently preselects the first language in the user settings when creating a new post or comment. This is a bad idea because this language might not actually be allowed in the community. It is better to pass the language as None if the user didnt specify it explicitly, because then the backend can smartly choose a language based on the overlap of user languages and community languages.
This fixes the problem described in
[this thread](https://lemmy.ml/post/1066608), where a user tries to post in a community that has only English allowed, with all languages enabled in user settings. In this case lemmy-ui preselects "undetermined language" as default, which is not allowed and results in an error. This PR fixes the issue because it lets the backend automatically select the correct …
=> Dont preselect new post language

src/shared/components/common/language-select.tsx
Fix https://github.com/LemmyNet/lemmy-ui/issues/1079
I've used the existing `language_select_placeholder` as I thought "Select language" is a good fit, but happy to change it simply `language` if preferred.
=> Fix aria-label for language select

src/server/index.tsx
Added "media-src *" to the http Content-Security-Policy header to allow non-local video files to display without getting blocked by CSP.
closes #1091
=> Add media-src * to Content-Security-Policy header to fix video posts with non-local links

src/server/index.tsx, src/shared/utils.ts
This solution isnt very clean, but it fixes the vuln in my testing and also doesnt break quotes as you can see below.
Using [this approach](https://stackoverflow.com/a/56596217) as replaceAll is not available.
=> Alternative way to sanitize isoData

src/shared/components/person/profile.tsx
Users can't view saved posts of other users, therefore we can hide the 'Saved' tab on all but your own profile page.
* fixes #1090
=> Only show 'saved' tab on own profile page

src/shared/components/common/language-select.tsx, src/shared/components/community/community-form.tsx, src/shared/components/person/settings.tsx
Community form should not show `undetermined_language_warning` warning. Since the component is shared between multiple forms a `hideLanguageWarning` prop was added so a specific instance can hide it.
Closes #1078
=> fix: Adds ability to hide language warning

src/shared/components/common/markdown-textarea.tsx
Added additional keybinds following #1136 and based on [Github md editor binds](https://docs.github.com/en/get-started/using-github/keyboard-shortcuts#comments).
I also made sure that when creating a list while text is selected, an additional space is added to make sure it is formatted correctly. This functionality is disabled when text is not selected so as to not change the current experience
=> Added additional keybinds

package.json
This setting is picked up by Corepack, and it's a way for others to concretely know which package manager they should use.
=> Specify package manager version in package.json

src/shared/components/comment/comment-node.tsx
Hi all!
Here's a quick PR to left-align the collapse/expand button on comment nodes. 
This is a pain point especially noticeable on mobile, when collapsing comments –different username lengths lead to the button being at different locations– forcing the user to hunt for the collapse button. It's very fatiguing. Having it left-aligned keeps it in the same place regardless of the other dynamic element widths.
Thanks so much!
=> Left-align comment collapse/expand button

src/shared/components/comment/comment-node.tsx
Hey! It looks like a style problem somehow slipped through in the last PR merge. It's causing the CI to fail in `main` and in recent PRs.
=> Run prettier

src/server/index.tsx, src/shared/components/common/html-tags.tsx
Fixes #1168
As there are issues with running the main branch with the current backend repo, I tested this by cherry-picking to `use_http_client_2`. 
My change fixes the linked issue by setting the `lang` attribute of the `html` tag properly in accordance to the lemmy user preferences or user-agent preferences. If the lemmy user has a UI language other than "Browser" set, then the response from the server will already have the correct `lang` set. Otherwise the attr is set on the client side according to the language settings in the browser. If any of this fails, it falls back to English.
=> Set html lang attr to the interface language

src/shared/components/common/pictrs-image.tsx
This adds a title tag to images, uses the alt tag value. This improves accessibility for sighted users and screen readers.
=> Add title to pictrs-image

src/shared/components/community/community-form.tsx, src/shared/components/community/create-community.tsx
Currently there's a bug preventing `CommunityForm` from being resubmitted after error. This PR handles the `loading` state on the parent component, properly setting `loading` back to `false` in case of an error.
https://github.com/LemmyNet/lemmy-ui/assets/35377827/c18b563f-c98e-43b2-ab55-2f6de5f93586
https://github.com/LemmyNet/lemmy-ui/assets/35377827/63688ea5-d8f0-4a5f-8a42-c694ae6d4f4d
=> Fix bug preventing `CommunityForm` from being resubmitted after error

src/shared/components/common/html-tags.tsx
Pretty simple change to fix #1259.
By default, `html-to-text` wraps lines at 80 characters. This resulted in poor compatibility with link previews in Discord (and I can imagine other platforms that don't handle this issue themselves). This change overwrites the default limit of 80 character lines (`wordwrap: false`) and retains the original post newlines (`preserveNewlines: true`).
=> Fix formatting of description meta tags

src/shared/components/post/post-listing.tsx
- Add missing tooltip for `cross-post` button on `PostListing`
Partially resolves #1238.
=> Add missing tooltip for `cross-post` button on `PostListing`

src/shared/components/post/post-listings.tsx
Before:
After:
Two changes:
* Add `border border-primary` to the `<hr>` but only if it is not the last item in the listing.
* Add typing information to `this.posts.map()` call
Fixed #533
=> Fix <hr> being almost invisible

src/server/index.tsx
This has been a personal pain point for me. I'll accidentally zoom slightly on mobile and the interface suddenly becomes much more difficult to navigate – forcing me to do a reverse pinch gesture. 😅
Likely resolves https://github.com/LemmyNet/lemmy-ui/issues/1220.
=> Prevent dragging zoom on mobile

src/shared/components/home/home.tsx, src/shared/components/home/login.tsx
Hey everybody! Proposal:
- Let's check `history.action` is `PUSH` (eg. there's *some* Lemmy page to go back to) and if so, use History API to go `back()` upon successful login. This will resolve https://github.com/LemmyNet/lemmy-ui/issues/1268.
Also included bugfix:
- Fix a bug, a pretty bad one, that became very noticeable while testing this feature. It prevents the user from navigating to `/` from `/login`, if `/login` is the first loaded page in that browser tab. I don't know if this is reported. Checking if `this.isoData.routeData.length` is falsey and some optional chaining fixes this right up. This only affects `>= 0.18` and seems to be related to the HTTP migration.
https://github.com/LemmyNet/lemmy-ui/assets/35377827/95386305-dd4e-4c27-886e-d984c536e015
Reproduction steps:
- Open …
=> Go back to previous page after login

src/assets/css/main.css, src/shared/utils.ts
=> Improve the look of tables

src/shared/components/common/html-tags.tsx, src/shared/components/common/moment-time.tsx, src/shared/components/person/settings.tsx, src/shared/i18next.ts, src/shared/utils.ts
Fixes #1205
I noticed that the linked issue could be solved by the `nonExplicitSupportedLngs` setting for i18next (see [here](https://www.i18next.com/overview/configuration-options#languages-namespaces-resources)), but the existing system for choosing the language bypassed the i18next code where that setting applied. Therefore I moved the code for getting languages into a simple `languageDetector` plugin for i18next.
For reference on these plugins, I used [the docs](https://www.i18next.com/misc/creating-own-plugins#languagedetector) and the source of the package [i18next-browser-languagedetector](https://github.com/i18next/i18next-browser-languageDetector).
I was then able to simplify some other code that references the current language by referring to the value tracked by i18next.
I've …
=> Match more specific locales to supported ones

src/shared/components/community/sidebar.tsx
A simple patch so that users can more easily subscribe to communities on other platforms.
Requires https://github.com/LemmyNet/lemmy-translations/pull/59.
Before:
After:
=> Make community IDs more easily selectable

src/shared/components/post/create-post.tsx
Hi Lemdevs!
In this PR:
- Fix a bug on `CreatePost` that causes the submit button to be stuck in a loading state if the `createPost` request fails.
Resolves https://github.com/LemmyNet/lemmy-ui/issues/1289.
Thanks!
=> Fix `CreatePost` infinite loading bug

Dockerfile, dev.dockerfile
This is an error I occured during building my own lemm-ui docker container from `dev.docker` due to not being able to use the ARM version right now (this is a separated issue, see https://github.com/LemmyNet/lemmy/issues/3102).
The error was:
```
#0 383.3 Arguments: 
#0 383.3 Directory: /usr/src/app/node_modules/inferno
#0 383.3 Output:
#0 383.3 env: can't execute 'node': Text file busy
#0 383.3 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: executor failed running [/bin/sh -c yarn --prefer-offline --pure-lockfile]: exit code: 126
```
To fix this error, we have to downgrade to Node 20.2 rather than 20.3 (see: https://forums.docker.com/t/getting-error-when-running-container-env-cant-execute-node-text-file-busy/136409). This …
=> hardcoded node version due to bug "Text file busy" error introduced in node 20.3

src/shared/components/home/admin-settings.tsx, src/shared/components/home/emojis-form.tsx, src/shared/components/home/rate-limit-form.tsx, src/shared/components/home/setup.tsx, src/shared/components/home/site-form.tsx, src/shared/components/home/tagline-form.tsx, src/shared/utils.ts
Hi Lemdevs!
This PR addresses some outstanding bugs in our admin settings panel –
- Tweak margin on icon & banner labels to match rest of form
- Add missing bind for `handleRemoveInstance` (ugh, I hate we have to do this!)
- Move `loading` state to `AdminSettings`, pass as prop to all children, which resolves some infinite loading issues
- Add util to properly validate allowed/banned instance TLD's
- Change admin settings header text from "Name/save your site" to "Setup/edit your site", which makes a lot more sense
Thanks!
=> Admin Settings: Bugfixes

src/shared/components/community/community.tsx, src/shared/components/community/sidebar.tsx, src/shared/components/post/post.tsx
It looks like a commit from yesterday broke some interactions in the sidebar. This PR only addresses blocking a community, but I can knock out the other bits tonight or tomorrow as well.
The specific issues addressed here are:
1. The community id being blocked was hard-coded to 0.
2. The loading icon would never go away since the sidebar has no way of knowing when the api request is done. I just removed that in this PR as it seems like the loading icon didn't exist before the commit yesterday and I'm not sure how to nicely implement that without some `thunk`-y mechanism.
=> fix "block community" functionality in sidebar

src/shared/components/home/login.tsx
Added error handling to the login form, so it doesn't just "spin infinitely" when there is an error. Error is surfaced as a toast using existing code, just calling i.setState() in the catch block.
=> Fix infinite spinner for login that results in failure

src/shared/components/post/post-listing.tsx
This vertically aligns the icons at the bottom of a post listing.
=> fix: Vertically align icons in post listing

src/assets/css/main.css, src/assets/css/themes/darkly.css, src/assets/css/themes/litely.css, src/shared/components/common/language-select.tsx, src/shared/components/common/markdown-textarea.tsx
Move test formatting bar above textarea, as per this comment: https://github.com/LemmyNet/lemmy-ui/pull/1288#issuecomment-1592786570
Note that this does this everywhere there is a markdown textarea, including in creating new posts, editing your bio, etc.
Also fixes:
- Create a "box" around the whoel markdown textarea/formatting bar so it's clear what you're formatting
- The "Post" button had a margin-right, not a margin-left as it should have
- Applied stylelint rules
- Fixed `.emoji-picker` selector
- Remove odd "button"-style formatting from language dropdown and its odd fixed/auto width behavior
=> feat: Move text formatting bar above textarea

src/shared/components/common/markdown-textarea.tsx
Per conversation #863, definitely should not be using inline `style` attributes, even though the Bootstrap colors don't quite work here. Should be fixed on the theming side, not by brute-forcing inline styles.
=> fix: Remove inline styles and use Bootstrap classes

src/assets/css/themes/darkly-red.scss, src/assets/css/themes/darkly.scss, src/assets/css/themes/litely-red.scss, src/assets/css/themes/litely.scss, src/shared/components/app/styles.scss
Sass files don't need to refer to full `node_modules` path
=> fix: Sass files don't need to refer to full node_modules path

src/assets/css/themes/darkly-red.scss, src/assets/css/themes/darkly.scss, src/assets/css/themes/litely-red.scss, src/assets/css/themes/litely.scss, src/shared/components/app/styles.scss
=> Revert "fix: Sass files don't need to refer to full node_modules path"

src/shared/components/common/markdown-textarea.tsx
These corners shouldn't be rounded; this fixes that.
=> fix: Fix rounded top corners in markdown textarea

src/shared/components/person/person-details.tsx, src/shared/components/person/person-listing.tsx
Addresses #1162. Unsure if I should open a separate issue for allowing instance admins to set their own default profile picture if they want.
Here is a post made by a user with a default pfp.
=> Add default profile picture for users who do not set one

.eslintrc.json, package.json, yarn.lock
Would be nice to have some basic a11y checks in here.
There are currently 25 violations; rather than fix all of them here, I've changed the severity of these rules to "warn". Ultimately they should be fixed and the severity overrides removed, but this will at least get some a11y linting in there and allow the thing to lint without errors for the time being.
=> feat(a11y): Add eslint-plugin-jsx-a11y

src/shared/components/home/signup.tsx, src/shared/components/person/settings.tsx
Instance admins can disable NSFW submissions for users on their instances. Currently, this option also removes the "show_nsfw" setting for all users, however, this doesn't really make sense - users are still able to subscribe to NSFW communities on other instances, and being able to control whether they see the posts there should be up to each user individually.
=> Don't hide "show NSFW" checkbox on instances that have NSFW disabled

src/shared/components/post/post-listing.tsx
Rather than having all those "advanced"/"more" buttons for a post in a horizontally-expanding row (which causes content to move around and causes the row to wrap, making the context of the buttons confusing), I've here tucked them away into a dropdown menu.
=> feat: Move advanced post menu into dropdown

.prettierignore
Prettier doesn't need to be applied to the generated theme CSS files
=> fix: Prettier ignore generated themes, as they aren't written by humans

src/assets/css/themes/_variables.darkly.scss, src/assets/css/themes/_variables.litely.scss, src/assets/css/themes/darkly-red.css, src/assets/css/themes/darkly.css, src/assets/css/themes/litely-red.css, src/assets/css/themes/litely.css, src/shared/components/post/post-listings.tsx
#1304 used the `primary` color for horizontal rules, which looks subtle-ish on dark mode, but less subtle on light mode.
It also increased the border width of the `<hr>`s.
This PR makes the colors more subtle, while still being visible, and modifies the Bootstrap `hr-border-color` variable for more global `<hr>` color fixing.
Would like feedback from @ayan4m1 and @SleeplessOne1917 on this, as they were responsible for the previous fix.
=> fix: Fix too-intense hr color between posts

src/shared/components/person/person-listing.tsx, src/shared/components/post/post-listing.tsx
=> fix: Fix post creator text alignment

src/assets/css/main.css, src/shared/components/post/post-listing.tsx
Some design work here, trying to tidy up all the metadata grouped together in the post details.
I've moved the link domain and the "expand" button to beneath the post title in small text. I think this makes it easier to parse the information.
=> feat(post): Move post domain beneath post title

src/shared/components/post/post-listing.tsx
The advanced button dropdown (where the report and block buttons are) was not showing on the post listing page if you were not the post author. This fixes that.
=> fix: Always show advanced post buttons dropdown

src/shared/components/person/password-change.tsx
The redirect to the home page after a successful password reset is currently broken, because the function references `this.props`, which is `undefined`. This PR fixes it.
Side-note: the `i` pattern that is used a lot in this project (including in this function) seems quite error-prone and not really idiomatic. Is there an explanation anywhere as to why this is done over just regular arrow functions + `this`?
=> Fix redirect after successful password reset

src/shared/components/post/post-listing.tsx
=> fix: Shrink and normalize some post action button colors and sizes

package.json
I've had new contributors ask on multiple occasions what to do when they can't get translations. Hopefully making this a script in package.json will make it easier to figure out for future contributors.
=> Add scripts to make managing translations easier

src/assets/css/main.css
Hi Lemdevs!
I propose we:
- Fix all `main.css` `var`s, recently broken by all our style tooling changes.
Resolves #1416.
Thanks!
=> Fix `main.css` variables

src/shared/components/app/navbar.tsx
The mobile nav bar stopped collapsing when a user clicks on a menu item or clicks outside the menu. This PR fixes that.
=> Fix mobile navbar bug

src/shared/components/post/post-listing.tsx
The icon and the title/aria/tippy text should be enough that people know what the number refers to. Trying to save a little more space in this row of buttons, especially on mobile.
=> feat: Hide 'comments' in post listing comments button

src/shared/components/home/home.tsx, src/shared/components/home/site-sidebar.tsx
#1355 added a dependency to Bootstrap Collapse JS for handling of sidebar collapsing. This reverts things to native Inferno state management.
=> fix: Remove Bootstrap JS in sidebars

src/shared/i18next.ts
This fixes the following error for me:
```
webpack://lemmy-ui/./src/shared/services/index.ts?:4
/* harmony export */   "UserService": () => (/* reexport safe */ _UserService__WEBPACK_IMPORTED_MODULE_1__.UserService)
^
TypeError: Cannot read properties of undefined (reading 'UserService')
```
=> fix: Fix i18n UserService import issue

src/server/index.tsx, src/server/utils/create-ssr-html.tsx
https://voyager.lemmy.ml is currently still having this error:
This is despite the fact that the `start_url` and url of the home page are the same. I'm hoping an appropriate file extension on the manifest will fix this.
=> (Hopefully) fix webmanifest different origin issue

src/server/handlers/manifest-handler.ts
This should reset the manifest stored in memory when the start url changes, while still not regenerating it more than it needs to.
=> Regenerate manifest on HTTPBase external change

src/server/handlers/catch-all-handler.tsx, src/server/handlers/manifest-handler.ts, src/server/utils/fetch-icon-png.ts, src/shared/utils/app/fetch-theme-list.ts
Hi Lemdevs!
I'm not sure what happened, but recent changes led to the server breaking today with `ReferenceError: fetch is not defined` as an error. It appears we already have `cross-fetch` as a dependency, but weren't using it anywhere. This PR utilizes it for shared/server use cases, ensuring it's both browser & Node friendly. Resolves the issue.
Thanks!
=> Fix grave `ReferenceError: fetch is not defined` error

src/server/utils/build-themes-list.ts
Duplicates were created because the custom themes were added to the global `themes` property each time the function was called.
Fixes #1411
=> Fix buildThemeList() function to ensure no duplicates

src/server/utils/create-ssr-html.tsx
Hi Lemdevs!
I propose we:
- Add a fallback `style` tag if backend is offline, ensuring _some_ theme is linked.
Before:
After:
=> Add fallback `style` tag for theme if backend offline

.github/ISSUE_TEMPLATE/BUG_REPORT.yml
`title` can't be left blank... apparently. This fixes things and restores ability to report bugs to this repo.
=> Fix broken `BUG_REPORT.yml` template

src/shared/components/home/home.tsx
Hi Lemmiaires.
In this PR:
- Fix inability to navigate to `Home` from `Settings` route, and probably other routes, too.
- Optional chaining resolves it
- Uh... don't know why TypeScript doesn't catch this
https://github.com/LemmyNet/lemmy-ui/assets/35377827/a8742620-0429-40ae-9509-b4472fbfa38a
Thanks.
=> Fix inability to navigate to `Home` from `Settings` routes

src/shared/components/home/home.tsx
Moved the scroll to top trigger into the state, and added a `setTimeout` to delay the `scrollTo` call until after the document renders with the post listing removed. Before the document rendering negated the `scrollTo` call on firefox. Not sure if this is the perfect solution, but has the desired effect.
=> Fix homepage `scrollTo(0, 0)` failing when document size changes.

src/shared/components/app/app.tsx, src/shared/components/community/create-community.tsx, src/shared/components/home/legal.tsx, src/shared/components/home/login.tsx, src/shared/components/home/setup.tsx, src/shared/components/home/signup.tsx, src/shared/components/person/password-change.tsx, src/shared/components/person/settings.tsx, src/shared/components/person/verify-email.tsx, src/shared/services/FirstLoadService.ts
Refactor of the fix implemented in #1528. This should prevent contributors from always needing to remember to manually call `FirstLoadService.isFirstLoad` in the constructors of new route page components even if they're not using it.
=> Refactor first load handling

src/shared/components/post/metadata-card.tsx, src/shared/components/post/post-listing.tsx
Hi Lemdevs!
In this PR:
- Handle embedded videos the same as other content (eg. click thumbnail to expand)
- Replace somewhat convoluted way of viewing content previously (clicking metadata card button and clicking another expand button)
Resolves #1556.
Thanks!
=> Handle embedded videos the same as other content

src/shared/components/post/post-listing.tsx
Adds some space between the comment symbol and new comment symbol on a post.
=> Add margin to new comment text

src/assets/css/main.css, src/shared/components/post/post-listing.tsx
Some links in post listings weren't changing color when hovered, and were using `text-` color classes instead of `link-` color classes. This tightens things up a little, for the post title link and URL subhead link.
=> feat(UI): Fix some link hover colors

src/shared/components/app/app.tsx, src/shared/components/community/community.tsx, src/shared/components/post/post.tsx
Now all pages have a main and aside element when a sidebar is present to facilitate custom theming. This does not impact the default behavior of the front.
~~Note: removed `ref={this.mainContentRef}` from the div element since it was flagged as an error, can't see  any impact but I don't know what it does in the first place.~~
=> Fix: missing semantic css classes and html elements

src/shared/components/post/post-listing.tsx
Hi Lemdevs!
In this PR:
- Remove extra expand icon on `PostListing`'s `postTitleLine`
- Why would a user want to expand a thumbnail? It's a confusing button.
Thanks!
=> Remove thumbnail expand icon on `PostListing`'s `postTitleLine`

src/shared/components/post/post-listing.tsx
Hi Lemdevs!
In this PR:
- Prevent `PostListing` previews from collapsing when voting
Resolves #1602.
Thanks!
=> Prevent `PostListing` previews from collapsing when voting

src/assets/css/main.css, src/shared/components/common/pictrs-image.tsx, src/shared/components/post/post-listing.tsx, src/shared/components/post/post-listings.tsx
Need opinions on this. This will reduce some visual noise and also tighten things up vertically a little.
=> feat(UI): Make post listing (icon) avatars smaller (line-height)

src/shared/components/post/post-listing.tsx
These were supposed to go away, I think I pulled them back in during a conflict
=> fix: Remove body preview

webpack.config.js
Without this, I kept getting docker errors on production builds: https://woodpecker.join-lemmy.org/repos/135/pipeline/870/7
=> Moving webpack-bundle-analyzer require inside mode check to fix docker.

src/shared/config.ts
This PR proposes reducing the default page size. It's certainly a change with some trade-offs, so feel free to reject it (or debate the extent of the reduction), but I will provide my argument below:
On lemm.ee, I have noticed that this small tweak has **vastly** improved the experience for our users. By reducing the page size in half, our page loads significantly faster, and server load has in general decreased slightly as well.
I will also share some actual stats. This was with `fetchLimit` set to 40:
And this is the same test run with `fetchLimit` reduced to 20:
Of course, the downside with this is that users need to load additional pages more often, but it seems like a small price to pay considering the performance benefits.
=> Reduce fetchLimit (40 -> 20)

src/shared/components/common/markdown-textarea.tsx
Hi Lemdevs!
In this PR:
- Fix borders on disabled `MarkdownTextarea` buttons when `props.isDisabled`.
Before:
After:
Thanks!
=> Fix borders on `MarkdownTextarea` buttons when disabled

src/shared/components/comment/comment-node.tsx
Hi Lemdevs!
In this PR:
- Make "Post Creator" badge stand out more by:
- Use "OP" shorthand label by default
- Add tooltip that says "Creator" upon hover
- Use `.text-info` color
This is a really important distinguishing badge on comments. I personally dislike the term "Original Poster", acronym "OP", but it has two advantages here: is shorter, takes up less room on row and is very familiar. So with that said, I agree with #1615. Debate on.
Resolves #1615.
Thanks!
=> Distinguish "Creator" badge on comments

src/shared/components/comment/comment-node.tsx, src/shared/components/person/profile.tsx, src/shared/components/post/post-listing.tsx
Appendum to #1656.
I did more testing with `lightly` and discovered we really aught to just use the default foreground colors for these pills, which means not manually specifying `text-black`/`text-white`, and just letting Bootstrap pick the default. This keeps things looking good across themes, see pics below.
=> Remove hard-coded `getRoleLabelPill` text foreground color classes

src/shared/components/post/post-listing.tsx
Hi all!
In this PR:
- Fix `PostListing` mobile margin layout issue
On mobile, the avatar of the user on the `createdLine` was touching the title of the post. It was bugging me. This fixes it.
Thanks!
=> Fix `PostListing` mobile margin layout issue

src/server/handlers/catch-all-handler.tsx
In this PR:
- Fix nonexistent property `req.cookie` from https://github.com/LemmyNet/lemmy-ui/pull/1713.
- Having no automated testing hurts with stuff like this. CI could have caught such a bug.
Thanks!
=> Fix nonexistent property `req.cookies`

src/shared/utils/app/setup-date-fns.ts
I realized that users who are still reporting issues with #1720 all have locales like `fr-FR`, the reason I could not reproduce the issue was that my browser was already setting it to `fr`.
Confirmed with two separate users that this solves the issue.
Fixes #1720
=> Fix date-fns locale import failing for some locales

src/shared/utils/app/setup-date-fns.ts
This date-fns locale bug is like a bossfight with multiple phases... hopefully this is the last phase 😅
Previously I fixed:
1. Other locales not loading at all https://github.com/LemmyNet/lemmy-ui/pull/1672
2. Locales like `xx-XX` (eg: `fr-FR`) failing to work, because for these date-fns expects just `xx` https://github.com/LemmyNet/lemmy-ui/pull/1721
These fixed the problem for most users, but turns out there are some locales out there which date-fns simply doesn't have support for. One example: `es-MX`. **For these users, the import still fails and Lemmy is still broken.**
This PR adds a fallback import of `en-US` when the user's locale is not availabe in date-fns.
=> Add fallback date-fns locale import

src/shared/services/UserService.ts
=> Fix jwt cookie path

src/shared/components/common/markdown-textarea.tsx
On MacOS, Ctrl is less commonly used than Command (⌘).
Javascript expresses command as `metaKey`.
This allows for _either_ Ctrl or Command to be used in the Markdown text area.
Note that on Windows, on some browsers, the "windows" key is labeled as meta, so it would work on windows as well.
http://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/metaKey
=> Add support for Command (⌘) key shortcuts on Markdown text areas

src/shared/components/private_message/private-message.tsx
The `PrivateMessageForm` decides whether it's being used for editing a DM or replying to a DM based on whether `privateMessageView` is `undefined`.
Currently in rc7, replying to private messages is impossible, as `privateMessageView` is passed in even when replying. Clicking the reply icon opens up an edit form, and saving this edit form generates an error (because you can't edit another person's DM).
This PR fixes the bug by removing `privateMessageView` from replies.
=> Fix DM replies not working

src/shared/components/common/markdown-textarea.tsx
Currently, when using the quote functionality in markdown editors (by highlighting some text before clicking reply/comment), the editor inserts "undefined" in front of quoted text:
This is due to a bug in the code which handles existing content in case of a quote being used. This PR fixes that bug.
(This PR also fixes the quoted text appearing appended on the end of the last line when editing existing messages)
=> Fix markdown editor quote bugs

src/shared/components/common/vote-buttons.tsx
=> fix: Fix vote buttons not showing spinners while registering vote #1761

src/shared/components/post/post-listing.tsx
A post that had only a body but no URL didn't have an expand button; this fixes that.
=> fix: Post expand button was not showing if body-only post

src/shared/components/common/searchable-select.tsx, src/shared/components/person/inbox.tsx, src/shared/components/search.tsx
Slight fixes to some inbox/search option filter alignments and page heading.
=> fix: Small cleanup to search/inbox controls

src/shared/components/comment/comment-node.tsx, src/shared/components/post/post-listing.tsx
Fixes an issue reported via matrix where `reason` was not set for certain mod actions.
=> Add missing modlog reasons

src/shared/components/comment/comment-node.tsx, src/shared/components/common/vote-buttons.tsx
Comment collapse and vote buttons were missing focus borders. This fixes that.
=> fix: Fix comment collapse and vote buttons not having focus style

src/shared/components/app/app.tsx, src/shared/utils/browser/data-bs-theme.ts, src/shared/utils/browser/index.ts, src/shared/utils/browser/is-dark.ts
=> fix: Add data-bs-theme attribute for user dark/light modes

src/shared/components/common/emoji-picker.tsx, src/shared/components/common/markdown-textarea.tsx
The markdown formatting toolbar buttons didn't have focus states on them. This fixes that.
Also refactoring the markdown image upload button to be a little more semantic.
=> fix: Add focus border to markdown toolbar buttons

src/assets/css/themes/_variables.scss, src/assets/css/themes/darkly-compact.css, src/assets/css/themes/darkly-pureblack.css, src/assets/css/themes/darkly-red.css, src/assets/css/themes/darkly.css, src/assets/css/themes/i386.css, src/assets/css/themes/litely-compact.css, src/assets/css/themes/litely-red.css, src/assets/css/themes/litely.css
Would like to hear some more feedback on this one.
#1591 reduced the base font size from 16px to 14px. Users have complained that this is too small.
- https://beehaw.org/comment/559815
Furthermore, this font size reduction was done on `$font-size-base`, when it should have been done on `$font-size-root`.
This PR unsets `$font-size-base` and changes `$font-size-root` to `93.75%`. This makes body text 15px (and `small` text `13.125px`), and also (by using `font-size-root` instead of `font-size-base`) results in more Bootstrap-adherent text size proportions.
User and Community avatars (the small inline ones on posts) go from a height/width of 18.38px to 19.69px. A very small change but not nothing ¯\_(ツ)_/¯
It might be worth considering unsetting `$font-size-root` entirely, so that body text …
=> fix: Revert smaller text size

src/shared/config.ts, src/shared/services/UserService.ts, src/shared/utils/browser/clear-auth-cookie.ts, src/shared/utils/browser/index.ts, src/shared/utils/browser/set-auth-cookie.ts
- Attempt to fix inability to logout from some instances (subdomains)
- Turn auth cookie setting/clearing into module actions for more visiblity
- Extract cookie name into config export
N/A
=> Attempt to fix inability to logout from some instances (subdomains)

src/client/index.tsx, src/server/handlers/catch-all-handler.tsx, src/shared/components/app/app.tsx, src/shared/utils/app/is-auth-path.ts, src/shared/utils/browser/data-bs-theme.ts
`data-bs-theme` wasn't being set as expected. This change should fix that.
=> Fix data-bs-theme

src/shared/components/common/user-badges.tsx
Making user badges styles a little subtler. Open to comment.
=> feat: Subtler user badge style

src/shared/components/home/home.tsx, src/shared/utils/helpers/get-query-params.ts
=> Fix home page not using site-level listing type #1612

src/shared/components/home/login.tsx, src/shared/components/home/setup.tsx, src/shared/components/home/signup.tsx, src/shared/components/person/password-change.tsx, src/shared/components/person/settings.tsx, src/shared/services/UserService.ts
- Add `showToast` param to `UserService`'s instance `login` method.
- Resolves #1784.
=> Don't show login toaster upon user settings change

src/shared/components/common/markdown-textarea.tsx, src/shared/components/post/post-listing.tsx
Post action buttons don't have focus ring color. Neither does the markdown help button. This fixes that.
=> fix: Add focus ring color to post action buttons and markdown help link

src/shared/components/app/footer.tsx
I think it makes sense to keep a link to the Join Lemmy website even though there's a logged in user. There's plenty of other useful info on that website beyond just joining Lemmy.
Using the URL avoids the phrase "Join Lemmy" and should indicate that you're navigating to said website.
Should address issue #1723
=> Use Join Lemmy hostname as link text in footer

src/assets/css/main.css, src/shared/components/post/post-listing.tsx
Mobile thumbnails weren't taking up their full width; this fixes that.
=> fix: Fix mobile thumbnail being too small

package.json, src/shared/markdown.ts, yarn.lock
[DenDen Markdown](https://conv.denshochan.com/markdown#ruby) is a popular implementation of ruby annotations in markdown, and a `markdown-it` extension already exists for it. By installing `markdown-it-ruby` the following markdown,
```markdown
{電子出版|でんししゅっぱん}を手軽に
```
will be converted into this HTML,
```html
<p><ruby>電子出版<rt>でんししゅっぱん</rt></ruby>を手軽に</p>
```
----
solves #1830
=> add ruby annotation support

src/shared/components/common/banner-icon-header.tsx, src/shared/components/home/site-sidebar.tsx
Fixes #1607 
Makes it so that the sidebar and banner don't appear in the same row.
=> fix: Adjust sidebar banner to wrap bellow the title

src/shared/markdown.ts
=> Fix XSS vuln

src/server/handlers/robots-handler.ts
Adds Disallow to the /modlog since it is not relevant for bots and as mentioned on /modlog the content may be disturbing. If search engines index the content on this page, it may negatively affect the Lemmy instance rank.
=> robots.txt: Disallow /modlog since it is not relevant for bots

src/shared/components/post/post-listing.tsx
Currently, the backend is copying images from federated posts locally and providing the URL as `thumbnail_url`. These images are mostly unused as the UI is preferring to use the post `url`, which in the case of images are from the originating instance.
This changes the logic on the UI to prefer the `thumbnail_url` of the local instance. It should help reduce the load on some of the larger instances while ensuring a good UX even if the origin instance is having connectivity issues. The change has been applied to my instance and appears to be working as intended. That said, I may be overlooking some edgecases.
I think this is ultimately a band-aid for now until we can come up with a more comprehensive solution for image proxying/caching on the backend.
=> Update post listing to prefer local image when available

src/shared/components/app/theme.tsx, src/shared/components/home/site-form.tsx, src/shared/components/person/settings.tsx
Allows setting the default theme as `compact` while respecting the browser default.
Related: https://github.com/LemmyNet/lemmy-translations/pull/82
=> Add theme option for compact that respects browser default

src/shared/components/modlog.tsx
This PR adds the community name to the "Featured post" action in the Modlog, so we can avoid having to open the post to figure that out.
=> Add community name to featured post action in Modlog

Dockerfile
Rather than running lemmy-ui as the root user in the container, run it as the `node` user provided by the node runner image.
N/A
The `node` process runs as `root`, which should be avoided if possible.
The `node` lemmy-ui process runs as the `node` user.
=> Use the 'node' user instead of root while running in a container

package.json, src/server/handlers/catch-all-handler.tsx, src/server/middleware.ts, src/server/utils/create-ssr-html.tsx, src/shared/interfaces.ts
As discussed in #1900, let's keep data serialized as before, but use a nonce to protect against malicious scripts.
Also removes unused websocket config related script tag.
=> Add nonce-based CSP header

src/shared/components/home/login.tsx
Right now if you try to login and you provide an unknown username/email or a wrong password, you will get no toast message. This PR adds toast messages for those scenarios and uses the messages already found in `lemmy-translations`.
=> Add Toast Messages for Bad Logins

package.json, src/server/index.tsx
I thought I had CSP properly disabled in dev mode in #1907, but turns out I was wrong (I think I had multiple solutions for this active parallel locally and I committed the wrong one)
This PR just disables CSP when `NODE_ENV=development` (which it is with build:dev)
Sorry if this caused any inconvenience for anybody!
=> Fix CSP in dev mode

src/shared/components/person/settings.tsx
This was mistakenly added by me to the user's settings page for languages. See: https://github.com/LemmyNet/lemmy-ui/pull/1870
=> Remove invalid default option from language list

package.json, webpack.config.js
Remove lodash.merge dependency from webpack.config.js file, replacing it with using [spread sintax](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Spread_syntax)
=> Remove lodash.merge dependency

src/server/utils/generate-manifest-json.ts
Lemmy's manifest is currently broken.
https://lemmy.world/manifest.webmanifest serves `"start_url":"http://lemmy.world","scope":"http://lemmy.world"` which doesn't match the scheme and is rejected by the browser.
This change makes it use "/" to keep things simple.
=> Fix start_url and scope in web app manifest

src/assets/symbols.svg, src/shared/components/common/password-input.tsx, src/shared/components/home/login.tsx, src/shared/components/home/setup.tsx, src/shared/components/home/signup.tsx, src/shared/components/person/password-change.tsx, src/shared/components/person/settings.tsx
Gives the user the ability to toggle the visibility of their password when using password input fields.
[Screencast_20230707_191946.webm](https://github.com/LemmyNet/lemmy-ui/assets/28871516/afb38546-a573-4bc1-a545-ae40c8d3fea4)
I also tweaked some parts of the settings page.
=> Add show/hide button to password fields

webpack.config.js
fixes #1911 `base.output` who needed deep merge 😞
=> Fix base.output (see #1911)

src/shared/components/community/communities.tsx
Fixes [#3500 mistakenly filed on the main repo](https://github.com/LemmyNet/lemmy-ui/issues/1941) by simply adding a sort dropdown to /communities using the existing `SortSelect` element. The right-justification of the search bar is preserved and the default sort is still `TopMonth`. The one issue is that the question mark should link to an explanation of community sorting, but the linked page on join-lemmy ([03 Votes and Ranking](https://join-lemmy.org/docs/users/03-votes-and-ranking.html)) only talks about post and comment sorting.
The functionality for sorting communities is already present in the API, so this feels like a no-brainer once join-lemmy is updated, which I'm happy to do as well if it needs doing.
Also, just a minor note, this also fixes a small inaccuracy where the bottom …
=> Allow sorting on /communities

src/shared/components/comment/comment-node.tsx
Quick fix for the comment HTML setup.  Changes it from two wrapping divs (header, comment/edit + footer) to three (header, comment/edit, footer) and adds accompanying classes.
No change afaict.  Checked locally.
=> Separate final comment row + add classes

src/shared/components/person/settings.tsx
The language selection in person settings currently only allows selecting from site languages. This doesnt make sense, as an instance may only allow eg German language for moderation purposes, but individual users still should be able to interact with remote content in different languages. This PR changes the selection to show all languages.
=> Allow selecting from all languages in person settings (fixes #1971)

src/shared/markdown.ts
Fixes #1976 by only allowing a very limited set of markdown rules for inline markdown rendering. 
Also fixes #1232
=> Allow limited set of markdown in title inline md rendering, fixes #1976

src/shared/components/comment/comment-node.tsx, src/shared/components/comment/comment-nodes.tsx
The comment report showed a dot because it was incorrectly a `<li>`
=> Fixing comment report showing dot.

src/shared/components/common/markdown-textarea.tsx, src/shared/utils/browser/index.ts, src/shared/utils/browser/platform.ts
On macOS, check for only the metaKey for keyboard shortcuts, since the ctrlKey is used for OS-specific shortcuts for navigating/editing text (like ctrl-b, ctrl-e, ctrl-k). Otherwise, check for the ctrlKey, on other platforms.
Relevant PRs: https://github.com/LemmyNet/lemmy-ui/pull/1136 https://github.com/LemmyNet/lemmy-ui/pull/1145 https://github.com/LemmyNet/lemmy-ui/pull/1750
=> Use proper modifier key in markdown text input on macOS

src/shared/components/home/emojis-form.tsx, src/shared/components/home/tagline-form.tsx
Fixes #2002
This restores the document title of the admin settings page by removing the document titles of the tagline and emoji forms, which appeared to be overwriting it. It seemed appropriate to outright remove them since these forms aren't being used anywhere else.
=> Fix document title of admin settings being overwritten by tagline and emoji forms

src/shared/utils/helpers/valid-title.ts
Should fix the issue #1962.
Also added Comments for clarity.
Expanded the RegEx in the validTitle helper function. 
Fixes #1962 
Invalid titles containing a new line character didn't return the correct value
Invalid titles containing a new line character return the right value
=> Expanded the RegEx to check if the title contains new line caracters. Should fix issue #1962

generate_translations.js
The translation submodule didn't have the latest from main, so I updated it.
This also fixes the linting error that is causing CI to fail.
=> Update translation submodule

src/shared/components/post/post-form.tsx
When importing title from an URL in **PostForm** some title provided by metadata contain whitespace "\s" chars that are converter to `&nbsp;` string during the post call.
This only fix the issue for the suggested title feature in frontend. 
The backend has also the issue when generating `embed_title` from the provided url.
**EDIT:** 
Another PR is now submitted to the backend and may also fix the issue on the frontend side: 
https://github.com/LemmyNet/lemmy/pull/3829
Exemple of title that contain the issue:
https://www.20min.ch/fr/story/espace-mise-en-orbite-reussie-pour-une-mission-lunaire-indienne-905291103206
=> Fix suggested title "&nbsp;" spaces

package.json, yarn.lock
For some reason, using newer version of babel broke the builds. This reverts babel to `7.21.5` to fix them.
=> Fixing webpack build.

src/shared/components/home/admin-settings.tsx
This moves the banned users admin area to its own tab. This makes it nicer to view the other admin settings when there's a large number of banned users and usernames aren't necessarily pleasant to see :slightly_smiling_face:
=> Move banned users to a separate admin tab.

src/shared/components/post/post-form.tsx
Moved title field to the top of the post-form.
Resolves #2039 
Resolves #2059
=> Moved title field to the top of post-form (#2039, #2059)

src/shared/components/home/instances.tsx
Also changed layout to show allowed and blocked side by side in columns instead of one giant list
Fixes: #2065 and other feature requests
[![](https://i.postimg.cc/NFx2t3pq/instances-page.png)](https://postimg.cc/xNc1yFwt)
=> Modify instances page to not link to blocked instances

src/shared/components/common/markdown-textarea.tsx, src/shared/markdown.ts
Instances federated with others (mostly hexbear) are finding that custom emojis on federated instance aren't rendered at the same size as locally. This change embeds a 'emoji' string in the markdown title to signify that it is an image that is intended to be rendered the same size as a local custom emoji.
=> Federate emoji sizing

src/shared/utils/helpers/format-past-date.ts
Improper date strings such as those very far into the future, or typo'd dates cause format-past-date to fail. This causes `modlog` page to load/spin forever instead of displaying any information as expected. This single file change adds error handling to the parse date function to skip improperly formatted dates, and log such to the console.
=> Added error handling to format-past-date to prevent timeouts on modlog

src/shared/components/post/metadata-card.tsx, src/shared/components/post/post-listing.tsx, src/shared/components/post/post.tsx, src/shared/utils/helpers/html-entities.ts, src/shared/utils/helpers/index.ts
does not fix backend, only frontend/lemmy-ui display
Convert simple html entities such as `&amp;` to `&` as expected for display of post titles.
Fixes: 
[pre fix](https://i.postimg.cc/wMhKjTp4/pre-amp.png)
[post fix](https://i.postimg.cc/kGr3CRkt/post-amp.png)
=> Improve handling/escaping of a few possible html entities for posts titles

src/shared/components/home/instances.tsx
Addresses #2065 
I think for most instances, the linked instance list will be longer than the allowed and blocked list, combined or not. So it made sense to join the allowed and blocked instance tables into the same column, to the right of the linked instance table.
If there were blocked instances, they would be shown in another table below `Allowed Instances`.
=> Move allowed and blocked instance tables to the column right of linked instance table

src/shared/markdown.ts
The `noopener` and `nofollow` rel tags are not set on links within markdown. Use the MarkdownIt standard way of adding  these attributes to links.
Did testing with linkify'd links as well as local instance parsed links.
N/A
=> Ensure markdown links have the noopener and nofollow rel tags

src/shared/components/community/community-link.tsx
I don't like the inconsistency of community names currently, the UI shouldn't be presenting things differently because of technical reasons that are hard for users to understand. This makes it easier to share communities with your friends!
=> always show community name with instance for easy copy-pasting to friends

package.json
- Context: https://typicode.github.io/husky/getting-started.html#yarn-2
Husky might not install correctly for yarn 2 installs. This should fix it.
=> Fix husky for yarn 2 .

src/shared/components/home/login.tsx
Before this change the user was not aware why the login failed unless they looked into the browser console, this simple change brings more errors to show up in a toast making it more clear and verbose what went wrong. Translations seem to be already in place. (https://github.com/LemmyNet/lemmy-translations/blob/38bb32f6898b227aaad06a48d8bf69a5b48416d6/translations/en.json#L433)
=> Display more information why has the login failed

src/shared/components/common/paginator.tsx, src/shared/components/community/communities.tsx, src/shared/components/community/community.tsx, src/shared/components/home/emojis-form.tsx, src/shared/components/home/home.tsx, src/shared/components/modlog.tsx, src/shared/components/person/inbox.tsx, src/shared/components/person/person-details.tsx, src/shared/components/person/registration-applications.tsx, src/shared/components/person/reports.tsx, src/shared/components/search.tsx, src/shared/config.ts
It may cause confusion to the user why pages in the community list are empty when there are no more communities to display. This small change fixes this issue by disabling the Next button if the number of fetched communities is less than the limit.
Additionally, I have moved the communityLimit constant to the config file.
The Next button will be still enabled, if there are exactly _{communityLimit}_ communities on the instance, to mitigate this the API would have to tell the client if currently viewed page is last, or the client could fetch next page in advance.
=> Disable "Next" button in Paginator when the next page is empty

src/shared/components/post/post-listing.tsx
Users that are not logged in should be able to use the existing button to show the raw markdown for a post.
The button can also be hidden with the viewOnly option in post-listing but I think this is the intended behaviour
Fixes https://github.com/LemmyNet/lemmy-ui/issues/2086
=> Don't hide the 'show source' button for anonymous users

src/server/middleware.ts
Cache headers have been active in production for a while now, and I didnt see any issues reported. So it should be save to increase the max-age to reduce server load further.
=> Increase cache-control max-age to 60s

src/shared/components/home/instances.tsx
Remove  `a href` attribute from instances on the `blocked` tab.
Fixes <https://github.com/LemmyNet/lemmy-ui/issues/2065>
[![blocked-instances.png](https://i.postimg.cc/7PSXzVqJ/blocked-instances.png)](https://postimg.cc/xqTKDLJ9)
Doesn't depend on but results are better, if the [Lemmy PR](https://github.com/LemmyNet/lemmy/pull/3957) - is approved as well.
=> Changed blocked instances to not be linked from instance page

src/shared/markdown.ts
Parse markdown in spoiler summaries (the text you see before expanding it)
Only the limited markdown parser with only emphasis, backticks and strikethrough allowed to prevent issues with unexpected content there.
=> allow limited markdown in spoiler summary

src/shared/components/person/inbox.tsx
Refetch the inbox when marking a message as read.
I would advise against just refiltering the messages due to the pagination. When a user marks a message as read and has more than 10 (or 20?) messages as unread, they will eventually run out of messages in the page, while still having unread messages.
Fixes https://github.com/LemmyNet/lemmy-ui/issues/2094
=> fix inbox read filtering

src/shared/components/person/settings.tsx, src/shared/routes.ts, src/shared/utils/app/index.ts, src/shared/utils/app/instance-to-choice.ts, src/shared/utils/app/update-instance-block.ts
This makes the UI able to take advantage of the [block instance feature](https://github.com/LemmyNet/lemmy/pull/3869).
=> feat: Block instance

package.json
Really weird husky issue that's causing the prod build to fail: https://github.com/typicode/husky/issues/945
Moved it from devDependencies to dependencies. It doesn't get bundled anyway so its nbd.
=> Husky fix for production build.

src/shared/components/person/profile.tsx
=> fix: Fix bug where user could not block person from profile page

src/shared/components/common/markdown-textarea.tsx
This PR resolves #2116 
Update: The behaviour is now a bit more similar to how Github handles this. I have also updated the video to show the new behaviour
Adds logic to detect if a paste event contains a URL. If true the URL will be formatted with the appropriate markdown. Open to suggestions on how to handle text selection after the paste event. The current implementation is demonstrated in the videos below.
It might also be better to implement this in the same way github does this, only adding formatting if text is already selected and otherwise just pasting the plain link, which might make things easier to read in the editor if no alternative link text is desired.
[Screencast from 2023-09-24 17-30-03.webm](https://github.com/LemmyNet/lemmy-ui/assets/19306765/9b175520-77fa-42af-880c-fe1 …
=> Smart url parsing

src/shared/components/app/navbar.tsx, src/shared/components/person/inbox.tsx, src/shared/services/UnreadCounterService.ts, src/shared/services/UserService.ts, src/shared/services/index.ts
Streamline the user experience by making the inbox counter more responsive.
Fixes https://github.com/LemmyNet/lemmy-ui/issues/1744
Right now, lemmy sends a cache header for some frequently queried data, like api/v3/user/unread_count or /api/v3/private_message/list of 60s.
When updating a message to be displayed as read, I would ideally like to just refresh the notification counter, but get old cached data from the browser.
@Nutomic @dessalines Is this caching behaviour intended or should it be changed on the backend? If a client is acting correctly, it should just avoid sending a request more than every minute but shortly after making changes, I think it would be wise to allow it to update.
An alternative might be to just update the view on the client and purely hope the server registers …
=> Improve notifications

package.json, src/assets/css/main.css, src/shared/components/comment/comment-report.tsx, src/shared/components/common/totp-modal.tsx, src/shared/components/community/communities.tsx, src/shared/components/community/community.tsx, src/shared/components/home/admin-settings.tsx, src/shared/components/home/home.tsx, src/shared/components/home/instances.tsx, src/shared/components/home/login.tsx, src/shared/components/home/setup.tsx, src/shared/components/home/signup.tsx, src/shared/components/modlog.tsx, src/shared/components/person/inbox.tsx, src/shared/components/person/password-change.tsx, src/shared/components/person/profile.tsx, src/shared/components/person/registration-applications.tsx, src/shared/components/person/reports.tsx, src/shared/components/person/settings.tsx, src/shared/components/person/verify-email.tsx, src/shared/components/post/create-post.tsx, src/shared/components/post/post-form.tsx, src/shared/components/post/post.tsx, src/shared/components/private_message/create-private-message.tsx, src/shared/components/remote-fetch.tsx, src/shared/components/search.tsx, src/shared/services/HomeCacheService.ts, src/shared/services/HttpService.ts, yarn.lock
This is an update so the UI works with the 2FA changes on the server side.
This is what shows when enabling 2FA:
[enable_totp_demo.webm](https://github.com/LemmyNet/lemmy-ui/assets/28871516/9a8479fb-a9b7-4425-8801-55718f109354)
This video shows using the new modal on the login screen:
[totp_login_demo.webm](https://github.com/LemmyNet/lemmy-ui/assets/28871516/39b71c2b-47a2-4c47-a960-43438c0a1d79)
This video shows how the modal works when entering 1 character at a time and hitting backspace, as well as what happens when an incorrect token is entered:
[totp_play_around.webm](https://github.com/LemmyNet/lemmy-ui/assets/28871516/dacdaf62-693c-452c-883a-9f2d39d5eec8)
Add translations
=> Totp change

src/shared/components/app/app.tsx, src/shared/components/common/anonymous-guard.tsx, src/shared/components/common/subscribe-button.tsx, src/shared/components/common/totp-modal.tsx, src/shared/components/home/login-reset.tsx, src/shared/components/home/login.tsx, src/shared/utils/app/index.ts, src/shared/utils/app/is-anonymous-path.ts
Fixes an issue where login screen could redirect to signup page after login. Also make guard for pages that should only be viewed when not logged in.
=> fix: Prevent login screen from redirecting to signup

Dockerfile, package.json, yarn.lock
Woodpecker can't build these because rxjs is missing. Not sure how it passes lint without it.
=> Fixing broken docker build due to missing rxjs.

src/server/index.tsx, src/shared/components/common/paginator-cursor.tsx, src/shared/components/community/community.tsx, src/shared/components/home/home.tsx
Adds cursor pagination by adding a `pageCursor` in place of `page` in the home and community urls.
Since the API doesn't return a `previous_cursor`, I had to use the back button for a previous, but it works well.
This breaks next page comment pagination (the first page shows fine), but we should probably do away with those at some point anyway.
=> Adding cursor pagination. Fixes #2155

src/assets/icons/favicon.svg
Removes Inkscape metadata and resulting unneeded XML namespaces
N/A - Icon looks identical before and after.
=> Simplify favicon by removing unneeded metadata

package.json, src/shared/markdown.ts
This PR will add Bi Directional text and RTL support to posts text.
However it will not fix comments text direction because the plugin I'm using `markdown-it-bidi` by @ahangarha doesn't support lists yet.
Partially fixes #347
=> Add RTL/BIDI to post text

Dockerfile
This change adds `curl` to the lemmy-ui container for basic Docker healthcheck purposes. The lemmy.world admins would like this as it can give more immediate feedback when performing site maintenance.
Without the change, any Docker healthcheck using `curl` will fail because the the command does not exist inside the container:
```
$ grep -A2 lemmy-ui docker-compose.yml
lemmy-ui:
image: dessalines/lemmy-ui:0.18.5
healthcheck:
test: curl -f http://127.0.0.1:1234 || exit 1
```
With the change, a simple `curl` healthcheck shows the lemmy-ui container as healthy when correctly configured:
```
$ grep -A5 lemmy-ui docker-compose.yml
lemmy-ui:
image: dvlemmyui
healthcheck:
test: curl -f http://127.0.0.1:1234 || exit 1
environment:
- LEMMY_UI_LEMMY_INTERNAL_HOST=lemmy:8536
$ docker ps | grep …
```
=> Add curl for basic healthcheck

src/shared/components/comment/comment-node.tsx, src/shared/components/community/community.tsx, src/shared/components/home/home.tsx, src/shared/components/person/profile.tsx, src/shared/components/post/post.tsx
Fixes an issue with comment actions "finishing" / closing the reply box
https://github.com/LemmyNet/lemmy-ui/assets/930215/0f3a37b4-7b61-46a6-8c23-421bce7c6950
=> Dont hide reply box on other actions. Fixes #1968

src/shared/components/common/totp-modal.tsx
While the 2FA modal doesn't seem as fancy with 1 text input as opposed to 6 small text inputs, this should prevent the janky behavior with phone keyboards.
=> Make 2FA input play nicer with phone keyboards

src/shared/components/home/login.tsx, src/shared/components/person/inbox.tsx, src/shared/components/person/registration-applications.tsx, src/shared/components/person/reports.tsx, src/shared/services/UnreadCounterService.ts
Refresh the notification counts when marking a report or application as done as well.
Also prevent unneccesary refetching of unchanged notification counts (don't need to refetch reports when marking a PM as read)
=> use improved notification system for all notification types

src/shared/markdown.ts
The sidebar will fail to render when a spoiler tag is used. This fixes the markdown parsing to no longer crash the front-end.
=> Fixed markdown parsing error particularly with the spoiler tag.

src/server/middleware.ts
voyager.lemmy.ml shows an image error when trying to add a QR code, because `blob:` is not in the csp. We wouldn't see this is testing as csp is disabled for testing.
=> Fixing QR code CSP.

src/server/handlers/catch-all-handler.tsx, src/shared/components/common/image-upload-form.tsx, src/shared/components/common/markdown-textarea.tsx, src/shared/components/home/emojis-form.tsx, src/shared/components/home/login.tsx, src/shared/components/home/signup.tsx, src/shared/components/person/inbox.tsx, src/shared/components/person/settings.tsx, src/shared/components/post/post-form.tsx, src/shared/services/HttpService.ts
lemmy-js-client now uses `Error` instead of string, breaking a few things. I changed the return type on the failed state, and fixed the other ones.
=> Fixing errors. Fixes #2216

src/shared/components/common/paginator-cursor.tsx, src/shared/components/common/paginator.tsx, src/shared/components/community/community.tsx, src/shared/components/home/home.tsx
As described in https://github.com/LemmyNet/lemmy/issues/4057 , it really doesn't make sense to show the previous button for paginatorcursor style paging. We can rely on the browser back button more reliably anyway.
Fixes #2197
=> Remove previous button for PaginatorCursor

package.json, src/shared/components/comment/comment-node.tsx, src/shared/components/comment/comment-report.tsx, src/shared/components/community/sidebar.tsx, src/shared/components/modlog.tsx, src/shared/components/person/profile.tsx, src/shared/components/post/post-listing.tsx, src/shared/components/post/post-report.tsx, src/shared/utils/roles/am-mod.ts, src/shared/utils/roles/index.ts, src/shared/utils/roles/is-admin.ts, src/shared/utils/roles/is-mod.ts, yarn.lock
Adds the new `creator_is_moderator` and `creator_is_admin` properties. Removes some pointless functions.
One other unfortunate thing: I still need to fill the list of moderators and admins into each post and comment listing. This is because the `canMod` functions still need the hierarchies of admins then mods, to make sure you can't do actions on mods / admins above you. Just knowing the creator is a moderator is unfortunately not enough info to know if you can do actions on them.
=> Adding creator_is_admin and creator_is_mod, removing pointless functions

package.json, src/server/handlers/catch-all-handler.tsx, src/server/handlers/manifest-handler.ts, src/server/utils/fetch-icon-png.ts, yarn.lock
Trying two different things to fix the SSR issue. But since I can't actually replicate the bug locally, these are just guesses.
- Removing `cross-fetch`. This seems to be abandoned, and everything appears to be working without it. I've also had some issues with it elsewhere.
- Fixing a minor issue with setting the headers.
=> Attempting to fix SSR. #2243

Dockerfile
This change improves the buildtime of the Docker container massively, by executing the build stage only once, instead of multiple times for each platform.
Currently when building the ARM64 image it is executing the build-stage under QEMU emulation, but after this change it re-uses the files build for AMD64 (since they are all javascript that does not matter).
=> Improve build performance

src/server/handlers/catch-all-handler.tsx, src/shared/services/HttpService.ts
wrappedhttpclient has two bugs:
1. setHeaders becomes async with errors gobbled up. this is probably not intentional and the result is not awaited at the call site
2. wrappedhttpclient overrides methods in the prototype and not the instance. this means that when a new instance is created, from then on all methdos on all wrappedhttpclients call the inner methods on the newly created client instead of their respective clients
this PR tries to fix both. it is untested so idk if it works
related: #2243
this might explain why the issue has only appeared now - previously the auth param was passed into all the http functions directly, but now it is fetched from the this on each lemmyhttpclient. and the this is often wrong due to the wrapper race condition
=> fix wrapped http client

src/shared/components/community/community.tsx, src/shared/components/home/home.tsx, src/shared/components/post/post-listing.tsx, src/shared/components/post/post.tsx
Doesn't fix the linked issue, but optimizes a few initial data fetches by using Promise.all
=> Adding a few promise.all concurrent fetches to FetchInitialData. #2234

src/shared/components/post/post.tsx
The banned toast was previously using the post creator, which is not necessarily the case.
=> Make sure banned toast has correct user.

src/assets/css/main.css
Closes #2264. The color I picked isn't perfect, but it's definitely easier on the eyes than what was there before.
=> Use highlight color for new comments on dark themes that won't burn your eyes out

src/assets/css/main.css, src/assets/css/themes/_variables.darkly-pureblack.scss, src/assets/css/themes/_variables.darkly.scss, src/assets/css/themes/_variables.i386.scss, src/assets/css/themes/_variables.vaporwave-dark.scss, src/assets/css/themes/darkly-compact.css, src/assets/css/themes/darkly-pureblack.css, src/assets/css/themes/darkly-red.css, src/assets/css/themes/darkly.css, src/assets/css/themes/i386.css, src/assets/css/themes/vaporwave-dark.css
Fixes #2264. Reverts changes from #2295.
Restores the background color for recent comments on dark themes to what they were in 0.18. 
In the Darkly theme on 0.18, recent comments used to be light grey, then in 0.19 they became yellow. I think this was caused by an update of Bootstrap to v5.3.2, which added a default value for the dark theme `bs-highlight-bg` variable in [bootstrap-utilities.css](https://github.com/twbs/bootstrap/commit/344e912d04b5b6a04482113eff20ab416ff01048#diff-26799cef23e0ac7c1c6e60651e6b4cf43b7a3effe86ad3bf616740b0bd783106R174). 
The correct highlighted comment background colors were in the `:root, [data-bs-theme=light] { }` section of each theme, but not in the `[data-bs-theme=dark] { }` section, so the values were getting overridden by Bootstrap's defaults. I …
=> Fix dark theme highlight color for recent comments, restores colors to 0.18 values

src/shared/components/post/post-listing.tsx
Currently, if auto_expand and blur_nsfw are active at the same time, NSFW images are auto expanded. I think it makes sense to not automatically expand NSFW posts if blur_nsfw is active while expanding SFW ones.
=> Do not auto expand media if blur_nsfw is active and the post is NSFW

.eslintrc.json, src/shared/components/post/post-listing.tsx, src/shared/interfaces.ts
Currently every video starts muted. With this PR, the volume value is kept in the window and used while playing other videos.
Husky auto formatting line 131 while commiting.
=> Store volume level on window object

Dockerfile
I've been building Lemmy UI using Node 21 since 0.19.0 without any issues, so it might be time to update the Dockerfile to use Node 21.
=> Update Dockerfile to Node 21

src/shared/components/home/signup.tsx
=> Fix captcha cache control bug

src/shared/components/comment/comment-node.tsx, src/shared/components/post/post-listing.tsx
Should fix #2304. Posts and comments will get fedi links when they are not local to the user's instance.
=> Fix fedi link regression

src/assets/css/themes/_variables.darkly-pureblack.scss, src/assets/css/themes/_variables.scss, src/assets/css/themes/darkly-compact.css, src/assets/css/themes/darkly-pureblack.css, src/assets/css/themes/darkly-red.css, src/assets/css/themes/darkly.css, src/assets/css/themes/i386.css, src/assets/css/themes/litely-compact.css, src/assets/css/themes/litely-red.css, src/assets/css/themes/litely.css, src/assets/css/themes/vaporwave-dark.css, src/assets/css/themes/vaporwave-light.css
Set themes to not decrease font size by default 
Fixes #2351
Admittedly it's a small difference the screenshots struggle to capture but one I can feel in a reduction of eye strain
=> increase font sizes on all themes

src/shared/components/common/content-actions/content-action-dropdown.tsx
… mod
When appointing or removing a mod the user name is printed instead of the community name.
=> Show the community name instead of the creator name when appointing mod

src/assets/css/main.css
Fixes #2350.
Not the ideal solution, as the user can still scroll while the modal is open. However, that is much better than having scrolling be unexpectedly broken.
=> Fix scroll bug when modal closes from browser back button

src/shared/components/app/app.tsx, src/shared/components/app/code-theme.tsx
In 0.19.3, `atom-lite` is used for code blocks and monospace even when the site or user uses a dark theme. This fixes that.
=> Make code blocks use correct theme when in dark mode

src/shared/components/person/settings.tsx
Since 0.19 there is a param `delete_content` for `/api/v3/user/delete_account` to avoid that deleting an account would automatically delete all posts. Looks like we forgot to add this option in the frontend.
https://github.com/LemmyNet/lemmy/pull/3817
Requires https://github.com/LemmyNet/lemmy-translations/pull/118
=> On account deletion add 'delete content' checkbox (fixes #2384)

.eslintignore, package.json, pnpm-lock.yaml, src/client/index.tsx, src/shared/build-config.d.ts, src/shared/build-config.js, src/shared/components/comment/comment-node.tsx, src/shared/components/common/markdown-textarea.tsx, src/shared/components/common/registration-application.tsx, src/shared/components/community/sidebar.tsx, src/shared/components/home/home.tsx, src/shared/components/home/legal.tsx, src/shared/components/home/signup.tsx, src/shared/components/home/site-sidebar.tsx, src/shared/components/person/profile.tsx, src/shared/components/post/post-listing.tsx, src/shared/components/private_message/private-message-report.tsx, src/shared/components/private_message/private-message.tsx, src/shared/dynamic-imports.ts, src/shared/lazy-highlightjs.ts, src/shared/markdown.ts, tsconfig.json, webpack.config.js
Adds a plugin to highlight.js to detect when code should be highlighted using a language that is not yet loaded. A wrapped call to `md.render` provides a callback that will be called after a language had to be loaded, this allows components to `forceUpdate`.
All available languages (listed here: https://highlightjs.org/download) are enabled and can be auto-detected.
Only the "common" set of 35 languages can be auto-detected, the remaining languages will be loaded individually on demand when explicitly specified by the author.
Uncommon languages, when auto-detected, are highlighted using the best fitting language of the common set.
`client.js` size shrinks by about 240kB (compressed)
=> Lazy loading less common languages for syntax highlighting

src/shared/components/home/login.tsx
=> Fix registration pending translation bug

.woodpecker.yml, package.json, pnpm-lock.yaml, src/shared/components/post/post-form.tsx, src/shared/components/post/post-listing.tsx
This adds the `alt_text` and `custom_thumbnail_fields` recently added to post forms.
=> Adding alt_text and custom_thumbnail to post form.

src/shared/components/person/settings.tsx
Resolves https://github.com/LemmyNet/lemmy-ui/issues/2413
=> Fix incorrectly escaped user export JSON

src/assets/css/main.css
Fixes #2394 
Add default bottom margin to `ul` and `ol` elements.
=> fix: add a default margin bottom to ul and ol in a comment field

src/shared/components/comment/comment-node.tsx
The same code is reused for the "show context" button as for the "link
to self" button. I'm not sure that's such a good idea in the long run.
There was a const `parentCommentId` that was always set even when not
having the `showContext` prop, causing the bug #2401.
=> Fix parent comment linking when not showing context

src/shared/components/common/url-list-textarea.tsx
Made a mistake when implementing this feature. The existing blocked URLs wouldn't show on load.
=> Correct mistake from block urls PR

src/shared/components/common/confirmation-modal.tsx, src/shared/components/common/content-actions/content-action-dropdown.tsx, src/shared/components/common/mod-action-form-modal.tsx, src/shared/components/common/totp-modal.tsx, src/shared/components/common/view-votes-modal.tsx, src/shared/components/mixins/modal-mixin.ts, src/shared/tippy.ts
This only starts rendering the dropdown and each modal dialog when they are shown for first time. For simplicity they keep getting rendered until the component unmounts.
A small fix when the Modal promise resolves after the component umounts. I don't remember how to trigger this, but saw this occasionally happen.
Also a work around for the tippy warning. Turns out tippy doesn't remove all event listeners when it destroys an instance.
=> Only conditionally render most of content action dropdown and workaround for tippy warning

src/shared/components/community/community-link.tsx, src/shared/components/person/person-listing.tsx
Everyone seems to like this one from jerboa anyway, so I'll add it here.
When its a non-local instance, always show the instance, but make it smaller and muted.
Didn't show instance name if a display name was set
Always shows it (for non-local)
(ignore the localhost string, that's just for testing)
=> Use muted display names, and always show instance for non-local. #1975 #2064

package.json, pnpm-lock.yaml, src/shared/components/common/media-uploads.tsx, src/shared/components/common/tabs.tsx, src/shared/components/home/admin-settings.tsx, src/shared/components/person/profile.tsx, src/shared/interfaces.ts
Adds the ability to view and delete media uploads for admins and users
https://github.com/LemmyNet/lemmy-ui/assets/930215/d2c942ea-e582-4aa4-87e8-fb00cd1e6d5a
context: https://github.com/LemmyNet/lemmy/pull/4631
=> Adding image upload views for admins and profiles.

src/shared/components/comment/comment-node.tsx, src/shared/components/comment/comment-nodes.tsx, src/shared/components/comment/comment-report.tsx, src/shared/components/common/vote-buttons.tsx, src/shared/components/common/vote-display.tsx, src/shared/components/community/community.tsx, src/shared/components/home/home.tsx, src/shared/components/person/inbox.tsx, src/shared/components/person/person-details.tsx, src/shared/components/person/profile.tsx, src/shared/components/person/reports.tsx, src/shared/components/person/settings.tsx, src/shared/components/post/create-post.tsx, src/shared/components/post/post-form.tsx, src/shared/components/post/post-listing.tsx, src/shared/components/post/post-listings.tsx, src/shared/components/post/post-report.tsx, src/shared/components/post/post.tsx, src/shared/components/search.tsx, src/shared/utils/app/calculate-upvote-pct.ts, src/shared/utils/app/index.ts, src/shared/utils/app/show-scores.ts, src/shared/utils/app/vote-display-mode.ts
This adds the ability to save your vote display mode preferences, and correctly renders those in comments and posts.
The `local_user_vote_display_mode.score` supercedes `local_user.show_scores`, but we'll remove that in a later update.
I have them all shown to demonstrate, but by default only upvote and downvote are shown. 
https://github.com/LemmyNet/lemmy-ui/assets/930215/e5e8d1f1-cdcc-4e6c-8d69-5545a571fd95
=> Adding vote display modes

src/shared/components/post/post-listing.tsx
Forgot to prevent videos and embeds from showing when I did the original adult consent modal PR.
=> Prevent videos and embeds from showing if adult consent not accepted

package.json, src/shared/components/person/profile.tsx
Hides the RSS button when viewing the `saved` view on profiles.
=> Hiding RSS button for saved view on profile page. Fixes #2438

src/shared/components/person/profile.tsx, src/shared/utils/helpers/index.ts, src/shared/utils/helpers/is-cake-day.ts
Profile displays the UTC+0 date to all users. This alters the effective cake day for some users, but prevents users in different timezones from seeing different dates. It also keeps showing the same date after switching timezones.
The tooltip for "Joined X months ago" still shows the localized exact time and date, which can be a different day than displayed below as "Cake day:".
=> Show same cake day date independent of timezone

src/shared/components/person/profile.tsx, src/shared/utils/helpers/index.ts, src/shared/utils/helpers/is-cake-day.ts
Closes #2441 
Besides fixing the bug listed in the issue, if a user creates their account on February 29th of a leap year, their cake day is March 1st for non leap years.
=> Fix leap year issue

eslint.config.mjs, src/shared/components/comment/comment-form.tsx, src/shared/components/comment/comment-node.tsx, src/shared/components/comment/comment-nodes.tsx, src/shared/components/comment/comment-report.tsx, src/shared/components/common/markdown-textarea.tsx, src/shared/components/community/community.tsx, src/shared/components/home/home.tsx, src/shared/components/person/inbox.tsx, src/shared/components/person/person-details.tsx, src/shared/components/person/profile.tsx, src/shared/components/post/create-post.tsx, src/shared/components/post/post-form.tsx, src/shared/components/post/post-listing.tsx, src/shared/components/post/post.tsx, src/shared/components/private_message/create-private-message.tsx, src/shared/components/private_message/private-message-form.tsx, src/shared/components/private_message/private-message.tsx, src/shared/components/search.tsx
- Disable submit buttons during submission (#2481)
- Re-enable submit buttons after failure
- Don't throw away user input on failure
- Keep navigation warnings enabled during submission
I used this snippet for testing, which selectively replaces the form with an empty object. It also adds a one second delay before the request is made. (Comment and post examples: [submit_buttons.webm](https://github.com/LemmyNet/lemmy-ui/assets/161147791/4a767c68-9234-4f61-8ab2-2a2078bcc511))
```diff
diff --git a/src/shared/services/HttpService.ts b/src/shared/services/HttpService.ts
index 7ff9121b..01a0cef7 100644
--- a/src/shared/services/HttpService.ts
+++ b/src/shared/services/HttpService.ts
@@ -1,3 +1,4 @@
+import { isBrowser } from "@utils/browser";
import { getHttpBase } from "@utils/env";
import { …
```
=> Fix some submit button issues

src/shared/components/person/settings.tsx
- Needed to wrap the fetchThemeList in an isBrowser check.
- Fixes #2497
This was crashing the UI server by trying to fetch the themelist locally, when it doesn't need to.
=> Fix 502 error on initial settings page load.

src/shared/components/post/create-post.tsx, src/shared/components/post/post-form.tsx
Fixes #2516 
Alternative to #2517
=> Fix copy title from metadata

src/shared/components/post/post-form.tsx
This stops `pnpm dev` from crashing when reloading `/create_post?url=https%3A%2F%2Fen.wikipedia.org%2F`.
Edit: has to be a `validURL`
=> Move fetchPageTitle into componentWillMount and only call client side.

src/shared/components/post/create-post.tsx, src/shared/components/post/post-form.tsx, src/shared/routes.ts
Clicking on another input element now moves the focus. Without this change the clicked input element is replaced with a new one during URL update.
=> Keep CreatePost mounted when updating URL, fixes focus resets.

.npmrc
I had to add ignore scripts to fix a one-off issue I encountered awhile ago. I tried running the app without the ignore scripts enabled anymore and it worked fine, os it seems that issue went away. We don't need this .npmrc anymore.
=> Remove ignore scripts

package.json, src/shared/components/post/post-listing.tsx
=> Fix auto download bug

src/shared/utils/helpers/get-query-string.ts
Browsers without size property for URLSearchParams always returned an empty string.
This could fix the broken inputs on iPadOs https://github.com/LemmyNet/lemmy-ui/issues/2542, as the size property is only available for Safari >= 17.
=> Fix getQueryString

src/shared/components/modlog.tsx
- Fixes #2590
Fixes modlog filtering to allow filtering by mods or admins.
=> Fixing modlog filtering to allow admins and mods to filter by mod.

src/shared/components/common/loading-skeleton.tsx, src/shared/components/home/home.tsx, src/shared/components/post/post-form.tsx, src/shared/config.ts
- This proved after time to be pointless. I thought about keeping the create and explore communities buttons, but these are already in the navbar, and so just take up more pointless space.
- Fixes #2027
- Fixes #2007
Removes the trending communities card block from home.
=> Remove trending communities card from home.

src/shared/components/common/password-input.tsx
Fixes #2381 using @richardARPANET 's suggestion.
Something I noticed working on this is that whitespace is allowed in passwords. This doesn't seem a problem in and of itself, but it's possible to make a password entirely from whitespace. Should this be allowed?
=> Remove min and max length from password input when using login form

src/shared/components/common/content-actions/content-action-dropdown.tsx, src/shared/components/common/markdown-textarea.tsx, src/shared/components/person/profile.tsx, src/shared/markdown.ts
Adds ability to view a users moderation history for their item.
Also fixed some tribute issues.
Profile page:
=> More moderation history

src/shared/components/post/post-form.tsx, src/shared/markdown.ts
This adds the ability to copy the download name from a torrent magnet link on post creation.
=> Add ability to fill magnet link title on post creation.

src/shared/markdown.ts
On serverside render, this customEmojis array gets appended to on every request. This eventually leads to Node.js killing the process for using too much memory.
=> Fix memory leak around emojis on server render

src/shared/components/post/post-listing.tsx
- Fixes #709
Video embeds were broken before, with this they show in the post:
=> Fixing peertube and ordinary video embeds.

src/shared/components/comment/comment-form.tsx
- Fixes #2624
Now the login and register links are separate. Before the entire block just went to the login page, now there are two links, one for login, the other for register.
=> Separating login and register links for must login alert.

package.json, pnpm-lock.yaml, src/shared/components/comment/comment-node.tsx, src/shared/components/common/modal/mod-action-form-modal.tsx, src/shared/components/home/site-form.tsx, src/shared/components/person/profile.tsx, src/shared/components/person/settings.tsx, src/shared/components/post/post-listing.tsx, src/shared/components/search.tsx, src/shared/utils/app/enable-nsfw.ts, src/shared/utils/app/is-post-blocked.ts, src/shared/utils/app/update-community-block.ts, src/shared/utils/app/update-instance-block.ts, src/shared/utils/app/update-person-block.ts, src/shared/utils/app/vote-display-mode.ts, src/shared/utils/helpers/get-bool-from-string.ts, src/shared/utils/helpers/index.ts
- Also fixing restore data on unban.
- Accounting for newly removed block views.
Some other things:
- I didn't use a checkbox, because it didn't inline correctly or look great, so this uses a checkbox-button.
- I *could* make it so this filter only shows up when searching for posts only, but then you wouldn't be able to use it when searching for `All` . 
This example has "grapes" in the body of a sample post, so when using the post title only filter, it returns nothing.
https://github.com/user-attachments/assets/59169151-fa40-4318-8ca8-d7cdddaa9dd2
cc @Nutomic
=> Adding a post title only filter to the search page.

src/shared/components/common/markdown-textarea.tsx
Fixes #1924
Title. This solution simply changes the order of the elements in the code. A shorter way would be to make `flex-direction: row-reverse;` but seems a bit overkill...
New to the contribution world, please let me know of any errors ^^
=> UX - Swap "Select Language" and "Cancel/Preview/Reply" button locations around in commentsReverse order of buttons in Reply TextArea

package.json, src/shared/components/community/community-form.tsx, src/shared/components/home/signup.tsx, src/shared/config.ts
Fixes #2206
Going off of [`is_valid_actor_name`](https://github.com/LemmyNet/lemmy/blob/cdc1cf3bf7afb8406d5eb55ee3a4f8adfebae71c/crates/utils/src/utils/validation.rs#L87) in the backend's codebase, Cyrillic characters should also be allowed.
=> Allow Arabic and Cyrillic characters when signing up or creating community

cliff.toml, src/shared/components/modlog.tsx
- Fixes #2794
Okay I've tested this now, and it works.
Mod ID filtering seemsto be broken, because its relying only on the hide_modlog_names setting.
Example: https://lemmy.ml/modlog?page=1&actionType=All&modId=1438729
The backend results seem to be fine, so this is a UI issue.
https://lemmy.ml/api/v3/modlog?page=1&mod_person_id=1438729
Edit: After this is merged, it needs to be cherry-picked to `release/v0.19`
=> Fix modlog mod_id filtering not working.

src/shared/components/common/markdown-textarea.tsx
Modify the logic for appending the URL after uploading an image, placing the image URL after the cursor.
- Use textarea.selectionStart to get the cursor position.
- Use string slicing (slice) to split the content at the cursor position.
- Insert the new content at the cursor position, instead of simply appending it to the end.
- Fixes #765
=> Modify the logic for appending the URL after uploading an image

package.json, pnpm-lock.yaml
#2833 doesn't bump the prettier version that's used in package.json, and causes a merge conflict. This PR does that version bump manually.
=> chore: Update prettier dev dependency

src/shared/components/common/markdown-textarea.tsx, src/shared/components/home/signup.tsx
Currently, users can click signup with empty Answer to get API error afterward. This PR enforces browser's required field validation to provide immediate feedback.
=> Enforce required validation on signup Answers 

src/assets/css/main.css
- Fixes #2878
Adds a bottom margin for details.
=> Adding a bottom-margin to spoiler details tag.

src/shared/components/post/post-listing.tsx
- Fixes #2826
If the embed_video is an actual video url, then prefer using the html `<video` over an `<iframe`
=> Using video tag for embed video urls that are videos.

src/shared/components/home/site-form.tsx, src/shared/components/post/create-post.tsx, src/shared/components/post/post-form.tsx, src/shared/components/post/post-listing.tsx
- Fixes #2885
Hides the NSFW field on create post for NSFW communities.
A back-end PR will also handle making that a default.
=> Hide NSFW field for create post form, for NSFW communities.

src/shared/components/common/password-input.tsx
- Fixes #2886
See linked issue.
@SleeplessOne1917 the only other case where `isNew` is used, is for autoComplete:
`autoComplete={isNew ? "new-password" : "current-password"}`
=> Fixing login password limits.

src/server/handlers/robots-handler.ts
This should prevent the various crawlers from overloading Lemmy instances. It is not officially part of robots.txt spec but many crawlers support it.
https://stackoverflow.com/a/9130248
https://imagesift.com/about
=> Add crawl-delay to robots.txt

src/shared/config.ts, src/shared/markdown.ts
The UI will now linkify @ user mentions of the format `@username@server.com` to point to the user's page, e.g. `https://example.com/u/user@server.com`
Fixes #2019
Fixes #2579
=> Add linkify user @ mentions

src/shared/components/comment/comment-node.tsx, src/shared/components/common/modal/view-votes-modal.tsx, src/shared/components/common/user-badges.tsx, src/shared/components/post/post-listing.tsx
Adds a new badge for "Banned from community", and adds the two banned badges to post listings and comment listings
- Fixes #2743
- Fixes #2095
- Requires https://github.com/LemmyNet/lemmy-translations/pull/158
<details>
<summary>Before/After Main Page</summary>
</details>
<details>
<summary>Before/After Banned User Profile</summary>
</details>
<details>
<summary>Before/After Banned User Comment</summary>
</details>
<details>
<summary>Before/After Moderator Vote View</summary>
</details>
=> Add banned badges to post and comment listings

src/shared/components/community/create-community.tsx
I tried to create a community and used a duplicate name. I found it a little confusing that I didn't get any error feedback. I tried to keep the error flow consistent with other code in the repo
-Fixes https://github.com/LemmyNet/lemmy-ui/issues/2348
-Fixes https://github.com/LemmyNet/lemmy-ui/issues/1374 (This looks like a duplicate)
=> Trigger toast error on community request failure

src/shared/components/private_message/private-message-report.tsx
Looks like post-report and comment-report already hide images using [hideImages](https://github.com/LemmyNet/lemmy-ui/blob/main/src/shared/components/post/post-report.tsx#L87) param.
The disadvantage with this is that the images are not rendered at all, not even as plain link. So there is no way to view the image or even to know that it is there.
=> Hide images in private message reports

src/shared/components/person/profile.tsx
RSS feeds are not implemented for uploads, and it wouldn't make sense to, similarly to saved posts as discussed in #2438
=> Hide RSS button for Uploads view on profile page

src/shared/components/person/profile.tsx
fixes #3070
Screenshot is from 0.19 backport - I don't currently have a test instance for main.
See #3070
See above
=> Only show View registration button to admins on profiles of local users

Dockerfile
Backport of #3089
- use cache mounts for package managers to allow reuse
- chown in COPY to final stage to avoid updating files again
- fix inconsistent capitalization in FROM/AS
This also almost halves the image size, as a separate chown after a COPY results in an additional layer, which duplicates all chowned files with updated ownerships.
It also reduces build time, especially in environments with slower storage, as the separate chown step also has to iterate over the entire directory tree.
References:
- https://docs.docker.com/reference/dockerfile/#syntax
- https://docs.docker.com/build/cache/optimize/#use-cache-mounts
- https://docs.docker.com/reference/dockerfile/#copy---chown---chmod
- https://docs.docker.com/reference/build-checks/from-as-casing/
`docker image ls …
=> [0.19] Optimize Dockerfile

src/server/index.tsx
Bug report: https://github.com/LemmyNet/lemmy-ui/issues/3106
Putting this for reference: https://expressjs.com/en/guide/migrating-5.html#path-syntax
=> fixed wildcard path matching syntax

src/shared/components/common/pictrs-image.tsx
I'm trying to get rid of our own fork :) I can create same PR for 0.19 if it makes sense.
=> Disable blur for NSFW images by default if content_warning exists

package.json, src/shared/services/UserService.ts, webpack.config.js
Fixes #2792
It turns out that the problem was just that a max age wasn't specified for the `instance-cache`. This PR makes it so everything in that cache expires in 10 minutes.
=> Remove instance cache

src/shared/components/common/user-badges.tsx
Fix displaying the deleted badge for users even if they don't have any other badge being displayed. Also changes the deleted badge for users from danger to info to make it more distinct from banned users.
from 0.19 branch:
=> Fix missing user badge for deleted users

src/shared/components/common/user-badges.tsx
Fix displaying the deleted badge for users even if they don't have any other badge being displayed. Also changes the deleted badge for users from danger to info to make it more distinct from banned users.
Backport of #3161
=> [0.19] Fix missing user badge for deleted users

src/shared/markdown.ts
Fixes lack of HTML escaping when custom emojis are used.
This also adjusts the emoji detection in the markdown image renderer to treat any image with a title starting with `emoji ` to be an emoji, appending the relevant classes for styling. This improves compatibility for emojis from other instances and also allows users to use self-defined emojis not defined in the instance custom emoji configuration.
=> Always escape HTML attributes in emoji autocomplete and custom emoji markdown renderer

src/shared/markdown.ts
Backport of #3168.
Also partially backports changes from #2715/#2718 to always use image attributes from markdown source instead of overwriting local emojis with the current custom emojis configured on the site.
Fixes lack of HTML escaping when custom emojis are used.
This also adjusts the emoji detection in the markdown image renderer to treat any image with a title starting with `emoji ` to be an emoji, appending the relevant classes for styling. This improves compatibility for emojis from other instances and also allows users to use self-defined emojis not defined in the instance custom emoji configuration.
When rendering markdown, Lemmy will no longer use the URL and alt text defined in the custom emojis on the current instance to replace the values in markdown but instead always use …
=> [0.19] Always escape HTML attributes in emoji autocomplete and custom emoji markdown renderer

src/shared/components/person/person-details.tsx, src/shared/components/person/profile.tsx, src/shared/interfaces.ts
Adds an option to view upvoted posts/comments in the Overview, Posts, and Comments views in the user's own profile.
The option is implemented as a separate row of buttons containing `Own` and `Upvoted` to show the user's own posts/comments or show the posts/comments the user upvoted, respectively.
The buttons are only shown in the user's own profile, and not in the `Saved` and `Uploads` views either.
The value of the buttons is stored in the URL as `&filter=`, similarly to `&view=`.
-Fixes #1673
-Fixes #2443
1. In spite of what #2443 claims, `disliked_only` to fetch downvoted posts/comments is not implemented AFAIK. (A separate issue for `Downvoted` should be opened?)
1. I think it's better like this, with separate buttons rather than new views (such as `Upvoted Posts` and `Upvoted …
=> Show upvoted posts, comments in user's profile

src/shared/components/person/person-details.tsx
Hide the next button for Overview, Saved, Upvoted views on users' profiles when there are no more posts or comments left. Like it's done for the Comments and Posts views already.
Issue persists on the Uploads view but that would require a bit more work.
=> Hide Next button for Overview, Saved, Upvoted

src/shared/components/comment/comment-node.tsx
This PR intends to increase target clickable area in furtherance of accessibility. Similarly to Reddit, allows the user to click anywhere alongside the byline (username, etc.) to collapse a comment. Affects URLs at `/post/*`.
Does not fix a separate issue.
This PR departs a bit from convention by exempting a code change from a couple of lint rules, and here is why I believe these are an exception. (For reference, the lint rules relate to clickable element requirements.): 
The button element for collapsing comments still exists as before, with the key and click handlers, and continues to serve as an accessibility-friendly way to toggle the `collapsed?` state of a CommentNode. This PR simply expands the clickable region (which is itself for accessibility reasons), but having screen readers …
=> Click anywhere on byline to collapse a comment

src/shared/components/comment/comment-node.tsx, src/shared/components/common/moment-time.tsx
Implements #3121: Don't show the edit mark in a comment if it was edited in less than 5 minutes from the moment it was published.
=> Don't show edit mark if comment was edited in less than 5 minutes

src/shared/utils/app/community-select-name.ts
Use `!name@example.com` instead of `example.com/name` to be more consistent.
=> Change display format for community name in search

src/shared/components/app/navbar.tsx
The username with dropdown on the top right somehow received an outline during 1.0 changes. Removing this to be consistent with 0.19
=> Remove outline for username button

src/shared/components/comment/comment-node.tsx, src/shared/components/common/modal/view-votes-modal.tsx, src/shared/components/common/user-badges.tsx, src/shared/components/person/profile.tsx, src/shared/components/post/post-listing.tsx, src/shared/utils/date.ts
Its a good idea to indicate new accounts. On one hand this makes it easy to welcome new users, on the other hand it can make mods aware of potential troll or alt accounts.
Translation: https://github.com/LemmyNet/lemmy-translations/pull/181
=> Add icon to indicate new accounts (fixes #2389)

src/shared/components/community/community.tsx, src/shared/components/person/profile.tsx
I wonder if there are any other params missing this decoding.
=> Fix Arabic user/community names (fixes #2207)

src/shared/components/post/post.tsx, src/shared/utils/app.ts
Seems like lemmy-ui assumes that parent comments are always listed first, but this is not the case anymore. Worth considering to fix this in the backend instead as it may affect other frontends too.
=> Fix "show context" (fixes #3496)

src/shared/components/search.tsx
Basically looks the same as comment listing on the homepage now.
=> In comment search results show post and community (fixes #1959)

src/shared/components/post/post-listing.tsx
- link-dark appears to be broken on many themes, including our default one. 
- Its safer to use text-body.
With a dark mode browser plugin:
=> Fix link-dark issues
