LemmyNet/lemmy-ui

- .gitmodules
- generate_translations.js
> Test submodules

- webpack.config.js
Project rebuilds in 3.5 seconds instead of 10 seconds.
> Use Webpack 5 filesystem cache

- src/client/index.tsx
- src/server/index.tsx
- src/shared/components/app.tsx
- src/shared/components/navbar.tsx
- src/shared/components/theme.tsx
- src/shared/initialize.ts
- src/shared/utils.ts
Fixes #45 
Also initialize more things in the entry points instead of inside Navbar
> Don't flash default theme on page load

- src/shared/components/post-listing.tsx
> Hide downvote on mobile when downvotes disabled

- .github/ISSUE_TEMPLATE/BUG_REPORT.md
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
- .github/ISSUE_TEMPLATE/QUESTION.md
I just copied this from the lemmy repo and adjusted the text "for frontend issues use lemmy-ui".
> Add issue template

- src/shared/components/community-link.tsx
- src/shared/components/community.tsx
- src/shared/components/iframely-card.tsx
- src/shared/components/inbox.tsx
- src/shared/components/instances.tsx
- src/shared/components/main.tsx
- src/shared/components/markdown-textarea.tsx
- src/shared/components/post-form.tsx
- src/shared/components/post-listing.tsx
- src/shared/components/private-message-form.tsx
- src/shared/components/sort-select.tsx
- src/shared/components/user-listing.tsx
- src/shared/components/user.tsx
> Removing targets

- src/assets/css/main.css
> Improve rendering in older browsers

- src/shared/components/post-listing.tsx
#221 needs to be merged first.
> Allow adding and removing remote mods

- .drone.yml
Same as https://github.com/LemmyNet/lemmy/pull/1557/
> Publish docker images from main

- .drone.yml
- package.json
- src/shared/components/navbar.tsx
- src/shared/components/person-listing.tsx
- src/shared/components/person.tsx
- src/shared/components/sidebar.tsx
- yarn.lock
- Fixes #246
- Changing preferred to display_name. Fixes #243
- Fixing a drone issue
> Moved ChangePassword to its own action.

- accessibility_tests.sh
- deploy.sh
- src/shared/i18next.ts
- test_deploy.sh
- update_translations.sh
This fixes the problem I mentioned in https://github.com/LemmyNet/lemmy-ui/issues/265#issuecomment-823419697
> Add check for unused languages in update_translations.sh

- CONTRIBUTING.md
> Fix link to docs in CONTRIBUTING.md

- src/shared/components/communities.tsx
- src/shared/components/community.tsx
- src/shared/components/inbox.tsx
- src/shared/components/main.tsx
- src/shared/components/modlog.tsx
- src/shared/components/paginator.tsx
- src/shared/components/person-details.tsx
- src/shared/components/search.tsx
> Always show previous paginator, extract paginator component.

- src/shared/components/person/profile.tsx
> Don't show your own subscribed on other users profiles.

- src/shared/env.ts
- src/shared/services/UserService.ts
- Couldn't add samesite due to isomorphic library.
- Couldn't add httponly, because the js needs it for calls.
- Fixes #389
> Adding JWT secure flag.

- src/shared/components/home/login.tsx
> Navigate away from login page if already logged in.

- src/shared/components/home/signup.tsx
Front-end solution to LemmyNet/lemmy issues #1955 and #1986 for future users
> Remove uppercase letters from the allowed username characters

- src/shared/components/home/signup.tsx
> Revert "Remove uppercase letters from the allowed username characters"

- src/shared/components/comment/comment-form.tsx
- src/shared/components/home/signup.tsx
- src/shared/env.ts
Move this to the top so that people see it before filling in all the information. 
I also noticed that this message is supposed to be highlighted (with classes `alert alert-light`), but in the default theme its just gray text on normal white background. It should be changed to be easily visible, with yellow background for example. Dont know how to do that though.
> Move lemmy.ml signup message to top of registration page

- package.json
- src/shared/components/comment/comment-node.tsx
- src/shared/components/home/admin-settings.tsx
- src/shared/components/post/post-listing.tsx
- src/shared/components/post/post.tsx
- yarn.lock
Still need to add leaving site.
> Don't allow transfer site.

- src/server/index.tsx
- src/shared/components/person/settings.tsx
- src/shared/utils.ts
Okay I fixed all the issues. Seems to work.
> Fixing custom themes.

- package.json
- src/shared/components/app/app.tsx
- src/shared/components/app/theme.tsx
- src/shared/components/home/site-form.tsx
- yarn.lock
It works, but the input looks a bit ugly. Not sure how to fix that.
> Add option to set site default theme

- src/shared/components/app/app.tsx
- src/shared/components/app/theme.tsx
- src/shared/components/modlog.tsx
New site setup failed because it tried to read the default theme from site.
> Fix error during new site setup

- package.json
- src/shared/components/comment/comment-form.tsx
- src/shared/components/comment/comment-node.tsx
- src/shared/components/post/post.tsx
- src/shared/utils.ts
- yarn.lock
> Adding mod / admin distinguish.

- src/shared/components/common/language-select.tsx
> Adding a warning for deselecting the undetermined language.

- src/shared/components/search.tsx
> Get rid of "No Results" showing while search is still loading.

- package.json
- src/assets/css/main.css
- src/client/index.tsx
- src/shared/components/app/navbar.tsx
- yarn.lock
There isn't an issue open for this one, but currently not all options in the mobile menu cause the nav to collapse. I also removed some excess HTML.
> Navbar hide menu fix

- CONTRIBUTING.md
The link in the CONTRIBUTING file was outdated
> Fix CONTRIBUTING link

- src/shared/components/post/post-form.tsx
> fix(#1067): Fix language not updating when editing post

- src/shared/components/common/markdown-textarea.tsx
Closes #901 
If you're happy with the approach, I'll go through and have a look at further keybinds and #984.
Although I think #984 might need further discussion. Perhaps a toggle somewhere to enable and disable this functionality. Once again, I'm happy to implement that too.
> Added Ctrl-K keybind

- src/shared/components/post/post-listing.tsx
> Fix typo in post-listing.tsx

- src/shared/components/common/markdown-textarea.tsx
> Add shortcut for submitting post

- src/shared/components/post/post-listings.tsx
- src/shared/utils.ts
as mentioned, 2 of the bugs I hit trying to run the new UI build on my home instance.
> Fix undefined value checks in use_http_client_2

- src/shared/components/home/login.tsx
- src/shared/components/home/setup.tsx
- src/shared/components/home/signup.tsx
- Remove whitespace from all username input fields
Resolves #1258.
> Remove whitespace from all username input fields

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
Changed how users should fill out git hub issues to be more in logic the the question asked.
> Changed required checkbox in github template

- package.json
- src/shared/components/community/community.tsx
- src/shared/components/community/sidebar.tsx
- src/shared/components/home/home.tsx
- src/shared/components/home/site-form.tsx
- src/shared/components/home/site-sidebar.tsx
- src/shared/components/post/post.tsx
- yarn.lock
> V18.0 additions

- src/assets/css/main.css
- src/shared/components/app/app.tsx
- src/shared/utils.ts
- Adds ability to press the "Tab" key to reveal a hidden "Jump to conent" link. Clicking or hitting enter will bring the post listings regardless of page into focus. 
- Prevents `validURL` from throwing exception into the browser console.
https://github.com/LemmyNet/lemmy-ui/assets/43147936/203ce936-8070-4ea3-8100-0be18233f3ad
closes #1117
> 1117 jump to main content

- src/assets/css/themes/_variables.darkly.scss
- src/assets/css/themes/_variables.litely.scss
- src/assets/css/themes/darkly-red.css
- src/assets/css/themes/darkly.css
- src/assets/css/themes/litely-red.css
- src/assets/css/themes/litely.css
Continuing some work from #1343, which had a couple issues.
> chore: Sass cleanup

- src/shared/components/post/post-listing.tsx
> feat: Badge-ify NSFW and removed by mod title info

- src/shared/components/post/post-listing.tsx
> fix(post): Fix missing labels on block/report buttons in new dropdown

- src/shared/components/post/post-listing.tsx
> feat(css): make vertical rhythm more consistent for post listings

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
Replaced a sentence referring to a the feature request as a bug report, and changed the title to refer to the UI of lemmy instead of simply lemmy, even though it was also technically correct before.
> Changed some text in feature request template

- src/shared/components/common/language-select.tsx
This select was missing the `custom-select w-auto` classes.
> Fix language missing class.

- package.json
- tsconfig.json
- webpack.config.js
- yarn.lock
@alectrocute Please let me know what you think of this approach
> feat: Drop dependency for tsconfig-paths-webpack-plugin

- src/shared/components/post/create-post.tsx
- src/shared/components/post/post-form.tsx
- tsconfig.json
This fixes the community not being selected by default when creating a post in a community. Also fixes a bug where changing some post form fields would reset other post form fields. Finally, updates translations because they are out of date.
> Com create post

- src/shared/components/common/language-select.tsx
- src/shared/components/post/create-post.tsx
- src/shared/components/post/post-form.tsx
Fixing a previous PR that I messed up.
> Post form adj

- src/client/index.tsx
- src/shared/components/common/tabs.tsx
- src/shared/components/home/admin-settings.tsx
- src/shared/components/home/rate-limit-form.tsx
- src/shared/components/person/settings.tsx
Added a lot of semantic/a11y improvements to tabs.
Works for me locally but would be good to test yourself before approving.
https://getbootstrap.com/docs/5.3/components/navs-tabs/#javascript-behavior
> fix(tabs): Fix tab semantics and a11y

- package.json
- src/server/handlers/catch-all-handler.tsx
- src/server/handlers/manifest-handler.ts
- yarn.lock
> Upgrade lemmy-js-client to `0.18.0-rc.2`

- src/shared/components/common/emoji-picker.tsx
The emojimart is currently offset, this centers it.
> Centering emojimart in view.

- src/shared/components/post/post-listing.tsx
> Cleaning up new comment badge. Fixes #1443

- src/shared/components/common/pictrs-image.tsx
> Fix avatar alignment issue

- src/server/utils/create-ssr-html.tsx
Closes #1473. Was unable to test locally as I would need to run this on a mobile device.
> Enable users to zoom on mobile

- src/shared/components/post/post-listing.tsx
Hi Lemdevs!
This is a pretty big bug. I attempted to fix our video embeds as quickly as possible before next release.
Before (completely broken):
After:
https://github.com/LemmyNet/lemmy-ui/assets/35377827/0dc3879f-a9b1-4c9b-8853-ea591294d0ff
Thanks!
> Fix video embeds

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
- .github/ISSUE_TEMPLATE/FEATURE_REQUEST.yml
Hi Lemdevs!
Last one, I promise! Caught some inconsistencies in the `ISSUE_TEMPLATE` now that it's actually working.
This should satisfy my OCD for many years to come.
Thanks.
> Minor `ISSUE_TEMPLATE` cleanup

- .github/ISSUE_TEMPLATE/BUG_REPORT.yml
Annoyingly enough, I forgot to remove these bullet list items that are totally out of place. This is my last PR related to this. Our templates should be top-notch now.
> Remove bullet list items from `ISSUE_TEMPLATE`

- src/shared/components/home/site-form.tsx
Sister PRs:
https://github.com/LemmyNet/lemmy-js-client/pull/149
https://github.com/LemmyNet/lemmy/pull/3158
> Remove federation worker count

- src/server/handlers/theme-handler.ts
Hi Lemdevs!
In this PR:
- Quiet "Can't set headers after they are sent" error, which is very noisy.
Resolves #1527.
Thanks!
> Fix noisy "Can't set headers after they are sent" error

- src/shared/components/search.tsx
> Fix search request being called twice on search page

- .eslintrc.json
My editor wasn't giving me Prettier warnings. This should fix that.
> chore(DX): Add prettier to eslint config for use with editors

- src/assets/css/themes/_variables.darkly.scss
- src/assets/css/themes/_variables.scss
- src/assets/css/themes/darkly-compact.css
- src/assets/css/themes/darkly-red.css
- src/assets/css/themes/darkly.css
- src/assets/css/themes/litely-compact.css
- src/assets/css/themes/litely-red.css
- src/assets/css/themes/litely.css
I think it's time. People seem to really not like how much space everything takes up. This could stand to be smaller, especially since so much of the text is UI, not body copy. The styles are responsive enough that people can zoom in and everything will work great.
> feat(UI): Reduce base font size

- src/shared/components/person/inbox.tsx
Hi Lemdevs!
In this tiny PR:
- Capitalize "Mark all as read" button on `Inbox`
Thanks!
> Capitalize "Mark all as read" button on `Inbox`

- src/shared/components/common/vote-buttons.tsx
Hi Lemdevs!
Just a little appendum to #1488 cc: @jsit .
In this PR:
- Use fragments instead of `<div>`.
- Fix Y-axis alignment of vote buttons.
Before:
After:
Thanks!
> Fix `VoteButtons` positioning

- src/shared/components/home/site-form.tsx
> Fix allowed and blocked instances not being fetched for admin settings

- src/shared/components/common/markdown-textarea.tsx
Apply feedback from https://github.com/LemmyNet/lemmy-ui/pull/1650/files#r1244112070.
Thanks!
> Use `classNames` in #1650

- src/shared/components/comment/comment-node.tsx
- src/shared/components/person/profile.tsx
- src/shared/components/post/post-listing.tsx
- src/shared/utils/app/get-role-label-pill.tsx
- src/shared/utils/app/index.ts
In this PR:
- Move `getRoleLabelPill` to `@utils/app`
Appendum to #1623.
Thanks!
> Move `getRoleLabelPill` to `@utils/app`

- src/shared/components/community/sidebar.tsx
Closes #1581.
Before
[Before](https://github.com/LemmyNet/lemmy-ui/assets/28871516/31546491-0281-45d6-894b-a858beae3aed)
After
[After](https://github.com/LemmyNet/lemmy-ui/assets/28871516/a652b325-a70a-4ce3-b245-465a8437ddb7)
> Fix subscribe and block community buttons not showing up on first load

- src/server/middleware.ts
> Allow audio captcha through CSP

- src/shared/components/home/setup.tsx
I tested this like 5 times locally, it worked.
> Fixing site setup. Fixes #1694

- src/shared/components/post/post-listing.tsx
Hi all,
In this PR:
- Fix missing classes on external link thumbnails with images
- Resolves #1693 
Thanks!
> Fix missing classes on external link thumbnails with images

- src/shared/components/home/home.tsx
- src/shared/components/home/tagline-form.tsx
Hi all,
In this PR:
- Fix taglines on `Home`
- Fix inability to edit taglines in admin panel
- Resolves #1688
Thanks!
> Fix taglines on `Home`

- src/server/middleware.ts
- src/shared/utils/app/is-auth-path.ts
- webpack.config.js
This is a 2 in 1, which closes #1704 and fixes a problem brought up in the dev matrix channel
> Fix some issues

- src/shared/components/post/post-listing.tsx
> fix: Fix thumb buttons having gray background #1754

- src/assets/css/main.css
- src/shared/components/common/vote-buttons.tsx
> fix: Fix vote buttons in list view variable width

- src/shared/components/community/sidebar.tsx
> fix: Fix joined button check color

- src/shared/components/app/error-page.tsx
- src/shared/utils/helpers/index.ts
- src/shared/utils/helpers/remove-auth-param.ts
- yarn.lock
> Prevent JWT token from showing up on error page

- src/shared/components/community/communities.tsx
- src/shared/components/community/community.tsx
- src/shared/components/community/create-community.tsx
- src/shared/components/community/sidebar.tsx
- src/shared/components/home/admin-settings.tsx
- src/shared/components/home/emojis-form.tsx
- src/shared/components/home/instances.tsx
- src/shared/components/home/login-reset.tsx
- src/shared/components/home/login.tsx
- src/shared/components/home/rate-limit-form.tsx
- src/shared/components/home/setup.tsx
- src/shared/components/home/signup.tsx
- src/shared/components/home/site-form.tsx
- src/shared/components/home/tagline-form.tsx
- src/shared/components/modlog.tsx
- src/shared/components/person/inbox.tsx
- src/shared/components/person/password-change.tsx
- src/shared/components/person/profile.tsx
- src/shared/components/person/registration-applications.tsx
- src/shared/components/person/reports.tsx
- src/shared/components/person/settings.tsx
- src/shared/components/person/verify-email.tsx
- src/shared/components/post/create-post.tsx
- src/shared/components/post/post-listing.tsx
- src/shared/components/private_message/create-private-message.tsx
- src/shared/components/search.tsx
Make sure all pages have an `<h1>`, and correct some `<h5>`s that can be `<h2>`s.
Retain text sizes, but bump up `<h1>`s that were `<h5>`s to `h4` text size.
> fix: Fix heading levels

- .github/pull_request_template.md
Adds a PR template for GitHub.
> feat: Add PR template

- src/server/handlers/catch-all-handler.tsx
> Fix search page breaking on initial load when logged in

- src/assets/css/themes/_variables.i386.scss
- src/assets/css/themes/_variables.vaporwave-dark.scss
- src/assets/css/themes/i386.css
- src/assets/css/themes/vaporwave-dark.css
- src/assets/css/themes/vaporwave-light.css
Post titles weren't showing up very well in the vaporwave dark and i386 themes. This fixes that.
> Dark theme tweaks

- package.json
- yarn.lock
Updates lemmy-js-client to 0.18.1 and lemmy-translations to 713ceed9c7ef84deaa222e68361e670e0763cd83
> Update lemmy-js-client and lemmy-translations

- src/shared/components/community/sidebar.tsx
This fixes leaving the mod team. It previously always removed the user with person_id 92.
NOTE: This has been tested :heavy_check_mark: :
> Set person_id to myId in handleLeaveModTeam

- src/shared/components/comment/comment-node.tsx
Make sure comment score color matches your vote.
> Make sure comment score color matches your vote.

- src/shared/components/common/password-input.tsx
- src/shared/components/home/setup.tsx
- src/shared/components/home/signup.tsx
- src/shared/components/person/password-change.tsx
- src/shared/components/person/settings.tsx
> Fix password autocomplete

- src/shared/components/post/post.tsx
- src/shared/utils/app/build-comments-tree.ts
See the issue for context.
https://github.com/LemmyNet/lemmy-ui/assets/930215/3b619226-daf7-4753-9543-5327b46dfdc3
https://github.com/LemmyNet/lemmy-ui/assets/930215/f6e619cd-ddf1-4d88-87e4-dfcb226e9ee6
> Fix comment insertion from context views. Fixes #2030

- src/shared/utils/helpers/format-past-date.ts
Fixes https://github.com/LemmyNet/lemmy-ui/issues/1899
Mostly just a temporary fix, since issue has been open a month and people need it. It looks like the backend is already setting large dates to NULL, as i had to manually edit my db to reproduce.
> Temp fix to modlog failing to render future dates

- src/shared/components/common/pictrs-image.tsx
Fixes #2072 
Modified the pictrs-image module to return webm as such instead of attempting to convert it to another format (like webp), which breaks the animation. 
https://postimg.cc/hf8Z5hDB
https://postimg.cc/nMXMctyN
> Improved webm handling for UI. Fixes #2072

- .woodpecker.yml
Adds a notify on failure, and tag deploy, and updates to the new steps syntax.
> Woodpecker updates.

- src/shared/components/post/post-listing.tsx
Fixes https://github.com/LemmyNet/lemmy-ui/issues/1884
Adds some margin above the purge button and ensure the button has the correct text displayed
> fix purge submit button

- src/shared/components/person/settings.tsx
> fix: Fix bug where old settings would linger on page until browser refresh

- src/shared/components/common/sort-select.tsx
Adds the scaled sorted option, and the translation.
> Adding scaled sort to UI. Fixes #2156

- .woodpecker.yml
Same as https://github.com/LemmyNet/lemmy/pull/4016
> Dont push to :latest docker tag

- src/shared/components/common/emoji-mart.tsx
- src/shared/components/common/emoji-picker.tsx
- src/shared/components/common/markdown-textarea.tsx
> fix: Fix emoji picker custom emoji bug

- src/shared/components/modlog.tsx
- src/shared/components/search.tsx
- src/shared/utils/helpers/dedup-by-property.ts
- src/shared/utils/helpers/index.ts
The seachable select inputs on the search page don't change what's picked in the select despite updating the url. This PR fixes that.
Fixes #2120
> Search page select fix

- src/shared/components/search.tsx
> Auto focus search input when navigating to search page

- src/shared/components/person/settings.tsx
Adds UI for the import and export settings feature.
https://github.com/LemmyNet/lemmy-ui/assets/28871516/2fcdee1a-b1a1-48ad-845e-07036b2ca9cf
> Settings Import/export

- src/client/index.tsx
- src/server/handlers/catch-all-handler.tsx
- src/shared/components/app/app.tsx
- src/shared/components/home/login.tsx
- src/shared/components/person/settings.tsx
- src/shared/utils/app/initialize-site.ts
- src/shared/utils/app/set-theme.ts
- src/shared/utils/browser/data-bs-theme.ts
- src/shared/utils/browser/index.ts
- src/shared/utils/browser/update-data-bs-theme.ts
Fixes #2166. The bootstrap theme originally did not change when switching between a light theme and a dark theme, which leads to the visual bug in the related issue.
> Update bs theme when site theme is changed

- src/shared/components/community/communities.tsx
- update_translations.sh
Fixing follow from the communities page.
> Fixing follow from subscribe page. Fixes #2215

- src/shared/components/person/settings.tsx
Found a few issues with instance blocking.
> Fixing instance blocking. Fixes #2245

- src/shared/components/common/vote-buttons.tsx
Disables the post voting buttons when logged out.
> Disable post voting buttons when logged out. Fixes #2248

- package.json
- src/server/handlers/catch-all-handler.tsx
- src/server/utils/has-jwt-cookie.ts
- src/shared/config.ts
- src/shared/services/UserService.ts
Changing the cookie name from `jwt` to `auth`
> Trying another SSR fix. #2243

- src/shared/components/comment/comment-node.tsx
> Fixing comments auto-collapsing. Fixes #2252

- package.json
- yarn.lock
Had a lot of very strange issues with cross-fetch: 4.0.0 , this fixes them.
> Fixing cross-fetch issues.

- .gitignore
- src/assets/css/themes/darkly-compact.css
- src/assets/css/themes/darkly-pureblack.css
- src/assets/css/themes/darkly-red.css
- src/assets/css/themes/darkly.css
- src/assets/css/themes/i386.css
- src/assets/css/themes/litely-compact.css
- src/assets/css/themes/litely-red.css
- src/assets/css/themes/litely.css
- src/assets/css/themes/vaporwave-dark.css
- src/assets/css/themes/vaporwave-light.css
Another premature / untested merge. These css files need to be in the repo, as they aren't auto-generated at all.
Reverts LemmyNet/lemmy-ui#2256
> Revert "Ignore autogenerated css files from being tracked in the repo"

- Dockerfile
Reverts LemmyNet/lemmy-ui#2261
> Revert "Improve build performance"

- src/shared/config.ts
See here: https://github.com/LemmyNet/lemmy/pull/4232/files/e553734b9c2a2bdbc7aef2bc4fd6dd7ed3bc4748#diff-d5fb8963b0b2349dfcaccc7b8ab084e8609e7ee134e587c9638414f9ed3fa0e6
> Changing auth cookie name back to jwt.

- src/server/handlers/manifest-handler.ts
- src/server/utils/generate-manifest-json.ts
This should hopefully address #2234
> Only generate manifest if it isn't already in memory

- src/shared/components/post/create-post.tsx
- src/shared/components/post/post-form.tsx
Using the communityToChoice function which smart-builds the label, to show a federated title, rather than only the regular title.
> Fixing communityToChoice. Fixes #2231 . Fixes #2232 .

- src/shared/components/post/post-listing.tsx
See linked issue. Removing the link target inferno `<Link` s
> Fixing link targets reloading page. Fixes #2275

- package.json
- yarn.lock
Upgrading lemmy-js-client to `0.19.0`
> Upgrading lemmy-js-client.

- src/shared/components/comment/comment-node.tsx
> Re-add show source for comments

- src/assets/css/themes/darkly-compact.css
- src/assets/css/themes/darkly-compact.scss
- src/assets/css/themes/darkly-pureblack.css
- src/assets/css/themes/darkly-red.css
- src/assets/css/themes/darkly.css
- src/assets/css/themes/i386.css
- src/assets/css/themes/litely-compact.css
- src/assets/css/themes/litely-compact.scss
- src/assets/css/themes/litely-red.css
- src/assets/css/themes/litely.css
- src/assets/css/themes/vaporwave-dark.css
- src/assets/css/themes/vaporwave-light.css
> Fix compact theme letter tail cutoff bug

- src/shared/components/app/error-page.tsx
- src/shared/components/post/post-listing.tsx
> Fix error page error interpolation

- package.json
- src/shared/components/common/content-actions/content-action-dropdown.tsx
- src/shared/components/common/view-votes-modal.tsx
- yarn.lock
Admins can now click post or comment dropdowns, and view their votes. Should help with vote-trolling.
- lemmy-js-client pr: https://github.com/LemmyNet/lemmy-js-client/pull/225
- lemmy back-end pr: https://github.com/LemmyNet/lemmy/pull/4332
https://github.com/LemmyNet/lemmy-ui/assets/930215/fedf406d-96fb-46ec-8285-25a1eb87e94d
> Adding admin view vote modal.

- src/shared/components/person/registration-applications.tsx
Adds a "Denied" view to registration applications, to make it easier to spot users circumventing denials.
Addresses issue #2321
Translation PR: https://github.com/LemmyNet/lemmy-translations/pull/111
> Add logic to filter view for denied registration applications

- src/shared/components/home/signup.tsx
Not necessary anymore: https://github.com/LemmyNet/lemmy/pull/4381
> Revert "Fix captcha cache control bug"

- package.json
- yarn.lock
Tried a few things, none of them worked. So just downgrading it now.
> Downgrade sharp.

- src/shared/components/common/markdown-textarea.tsx
> Hide WYSIWYG buttons when previewing markdown

- src/shared/config.ts
> Fix links to users and communities not including query in hyperlink

- .github/CODEOWNERS
Its been many months since they've been able to contribute.
> Removing alectrocute and jsit from codeowners.

- src/shared/components/common/registration-application.tsx
> Show user email in registration application

- src/shared/components/private_message/private-message-form.tsx
> Add matrix account link to create private message form

- .woodpecker.yml
See change in `.woodpecker.yml`
> Fix tag failure notifs.

- src/shared/components/common/image-upload-form.tsx
- src/shared/components/common/pictrs-image.tsx
- src/shared/utils/app/setup-date-fns.ts
> chore: fix some comments

- Dockerfile
Gonna merge this so I can get a beta release out.
> Using corepack to install pnpm, instead of npm -g

- src/server/handlers/catch-all-handler.tsx
- src/server/utils/create-ssr-html.tsx
- src/shared/components/app/app.tsx
- src/shared/components/common/adult-consent-modal.tsx
- src/shared/components/post/post-listing.tsx
- Require consent of logged in existing users.
- Prevent link clicks in blurred areas.
- Enable tippy again.
- Prevent stacking of countdowns for Back button.
- Fix auto expand blocking for images.
> Content warning fixups

- dev.dockerfile
Forgot to use `corepack enable` for the dev Dockerfile as well.
> Fix dev dockerfile

- package.json
- src/shared/components/community/create-community.tsx
> Fix bug where newly created communities cannot be edited until refresh

- package.json
- src/shared/components/home/admin-settings.tsx
Addresses #2454.
Was only able to reproduce that issue with the admin settings. Adding in a refresh after saving does the trick.
> Refresh admin settings on submit

- src/shared/components/post/create-post.tsx
- src/shared/components/post/post-form.tsx
- src/shared/components/post/post-listing.tsx
> Fix Language not allowed infinite loading on failed post

- renovate.json
Seems easier to have them run and merge them as soon as they come in.
> Remove renovate schedule.

- package.json
- pnpm-lock.yaml
> Upping lemmy-js-client_version.

- src/shared/components/common/image-upload-form.tsx
- src/shared/components/common/markdown-textarea.tsx
- src/shared/components/home/emojis-form.tsx
- src/shared/components/home/home.tsx
- src/shared/components/post/create-post.tsx
- src/shared/components/post/post-form.tsx
- src/shared/interfaces.ts
> Create post query params

- src/shared/components/person/profile.tsx
> Make uploads only viewable to oneself

- src/assets/css/themes/darkly-compact.css
- src/assets/css/themes/darkly-pureblack.css
- src/assets/css/themes/darkly-red.css
- src/assets/css/themes/darkly.css
- src/assets/css/themes/i386.css
- src/assets/css/themes/litely-compact.css
- src/assets/css/themes/litely-red.css
- src/assets/css/themes/litely.css
- src/assets/css/themes/vaporwave-dark.css
- src/assets/css/themes/vaporwave-light.css
Regenerate CSS to use latest bootstrap stuff
> Regenerate themes

- src/shared/components/home/admin-settings.tsx
> Leave admin confirmation

- src/shared/components/home/rate-limit-form.tsx
Adds a rate limit info message:
> Add rate limit info message.

- src/server/utils/create-ssr-html.tsx
- src/server/utils/generate-manifest-json.ts
> Prevent broken logo from crashing site

- src/shared/components/comment/comment-node.tsx
> Fix wonky comment action icon button alignment

- src/shared/components/post/create-post.tsx
- src/shared/components/post/post-listing.tsx
- src/shared/utils/types/cross-post-params.ts
Fixes #2605
I also made nsfw and language cross-postable.
> Make more post params cross-postable

- renovate.json
These updates were getting a bit annoying.
> Adding renovate schedule.

- src/shared/components/person/settings.tsx
- Fixes #2667
This is unused now.
> Remove show new post notifs setting.

- src/shared/utils/browser/clear-auth-cookie.ts
- src/shared/utils/browser/set-auth-cookie.ts
- Fixes #2666
- Fixes #2601
See the above issues for context.
> Changing sameSite cookie from Strict to Lax.

- src/shared/components/community/community.tsx
> Dont simplify cross-posts for a community feed.

- .woodpecker.yml
Just fixes a few woodpecker warnings.
> Fixing woodpecker warnings.

- src/shared/components/post/post-form.tsx
- src/shared/components/post/post-listing.tsx
- src/shared/utils/helpers/get-unix-time.ts
@Nutomic I made some fixes that you can see here.
> Adding i18n, and fixing some fields

- src/shared/components/app/app.tsx
> Fix jump to content

- renovate.json
This should be updated manually as it usuall has breaking changes. See https://github.com/LemmyNet/lemmy-ui/pull/2749
> Ignore updates for lemmy-js-client

- src/shared/services/I18NextService.ts
> Adding nynorsk language.

- src/shared/components/post/create-post.tsx
- src/shared/components/post/post-listing.tsx
- src/shared/utils/types/cross-post-params.ts
Fixes https://github.com/LemmyNet/lemmy-ui/issues/2688
> Add Thumbnail URL When Crossposting

- src/shared/components/comment/comment-node.tsx
- src/shared/components/post/post-listing.tsx
> Adding fedilink translation for link titles.

- src/shared/utils/app/setup-date-fns.ts
> Adding zh-CN as default for zh lang.

- src/server/handlers/robots-handler.ts
- src/server/handlers/security-handler.ts
> Fix indentation for robots and security handler txts.

- src/shared/components/post/post-listing.tsx
Adds the local post link to post listings. 
-Fixes #2160
-Fixes #2159
> Add local link next to fedilink on posts

- src/shared/components/home/donation_dialog.tsx
- src/shared/components/home/home.tsx
Made a few fixes to this, to use bootstrap alerts. Also the dismissing is working now.
> A few fixes to the donation dialog.

- src/shared/components/home/signup.tsx
This message was added long ago when lemmy.ml had the majority of Lemmy users. Now it only represents 4% of active users so its not necessary anymore.
https://github.com/LemmyNet/lemmy-translations/pull/164
> Remove signup message specific for lemmy.ml

- src/shared/components/home/donation_dialog.tsx
https://github.com/LemmyNet/lemmy-ui/pull/3056#discussion_r2032768311
> [0.19] Remove dangerous inner html for donation dialog

- .gitmodules
https://github.com/LemmyNet/lemmy-ui/pull/3075#issuecomment-2789852920
> [0.19] Use main branch of lemmy-translations

- src/server/handlers/robots-handler.ts
> feat: add extra items to robots.txt disallow

- src/server/handlers/catch-all-handler.tsx
- src/shared/interfaces.ts
- src/shared/utils/env/get-external-host.ts
- webpack.config.js
> [0.19] Remove LEMMY_UI_LEMMY_EXTERNAL_HOST from webpack.DefinePlugin

- src/shared/components/home/donation_dialog.tsx
> [release/v0.19] Use alert-info for donation dialog

- src/server/index.tsx
> Fixing cache-control header. [release/v0.19]

- package.json
- src/shared/services/UserService.ts
- webpack.config.js
Backport of the caching fix from #3105.
> Remove instance cache [release/v0.19]

- src/shared/components/community/sidebar.tsx
Add search bar to community sidebar as [discussed on Lemmy](https://lemmy.ml/post/32355919/19527965).
> [0.19] Add search field to community sidebar

- src/shared/components/search.tsx
This is done in the backend now, see https://github.com/LemmyNet/lemmy/pull/5752
> Dont call resolveObject for search

- src/shared/components/home/donation_dialog.tsx
> Use alert-info for donation dialog

- .prettierignore
- package.json
- pnpm-lock.yaml
Uses a maintained library to sort the package.json.
> Use a better library to sort package.json

- .prettierignore
- scripts/test.sh
- src/shared/components/person/settings.tsx
- src/shared/utils/app.ts
- Adds *UserBlockInstancePersons* alongside the already-existing *UserBlockInstanceCommunities*.
- Also cleans up some of the i18n code for blocking / unblocking items.
- Fixes #3286
> Add ability to block all persons from an instance.

- src/shared/components/home/admin-settings.tsx
- This was mostly completed by @matc-pub, but I added the filters, and changed the tab from *banned* to *users*.
- Fixes #3278
https://github.com/user-attachments/assets/f920d61f-3bdf-4eb3-8ffd-cb0b80857603
> Add ability to show banned users and all users.

- src/shared/components/comment/comment-node.tsx
- src/shared/components/search.tsx
- Fixes #3398
https://github.com/user-attachments/assets/0087fa93-d6f9-4125-9494-58b81a310580
> Collapse removed comments that have no children by default.

- src/shared/components/modlog.tsx
Defined here: https://github.com/LemmyNet/lemmy/blob/main/crates/db_schema/src/lib.rs#L96
> Add new modlog filters

- src/shared/components/community/community-link.tsx
- src/shared/components/modlog.tsx
> Fix community link in modlog title (fixes #2209)

- src/shared/components/community/sidebar.tsx
- src/shared/components/post/create-post.tsx
Desktop:
Mobile:
By the way sidebar text is not being rendered currently, probably requires update of js-client.
> Show sidebar on create post page (fixes #1522)

- src/shared/components/comment/comment-node.tsx
- src/shared/components/comment/comment-nodes.tsx
- src/shared/components/comment/comment-report.tsx
- src/shared/components/common/content-actions/content-action-dropdown.tsx
- src/shared/components/community/community.tsx
- src/shared/components/home/home.tsx
- src/shared/components/person/notifications.tsx
- src/shared/components/person/person-details.tsx
- src/shared/components/person/profile.tsx
- src/shared/components/post/post-form.tsx
- src/shared/components/post/post-listing.tsx
- src/shared/components/post/post-listings.tsx
- src/shared/components/post/post-report.tsx
- src/shared/components/post/post.tsx
- src/shared/components/search.tsx
> Block community from context menu (fixes #3306)
